import type { IconName } from "@/components/icon";
import type { Body } from "@/lib/sky";

/**
 * minAltitudeDeg: https://en.wikipedia.org/wiki/Air_mass_(astronomy)#cite_ref-3:~:text=Pickering%20(2002)%20developed
 * maxSunAltitudeDeg: https://www.hnsky.org/sqm_twilight.htm
 * maxCloudPct: https://www.cleardarksky.com/c/DSPNMkey.html
 * maxMoonIllum: https://articles.adsabs.harvard.edu/pdf/1991PASP..103.1033K
 */

export type Target = {
    id: string;
    name: string;
    kind: "planet" | "moon" | "sun" | "star" | "galaxy" | "nebula" | "cluster";
    interest: "Planets" | "Moon" | "Sun" | "Stars" | "Galaxies" | "Nebulae";
    blurb: string;
    magnitude: number;
    sizeArcmin?: number;
    /** fixed objects: J2000 right ascension / declination, degrees */
    ra?: number;
    dec?: number;
    /** moving objects: run through the ephemeris instead of ra/dec */
    body?: Body;

    minAltitudeDeg: number;
    /** How dark it has to be: 0 sunset, -6 civil, -12 nautical, -18 astronomical dusk. */
    maxSunAltitudeDeg: number;
    /** Weather requirement: cloud cover percentage this can tolerate. */
    maxCloudPct: number;
    /** Moonlight this can tolerate, 0..1 lit fraction. 1 = doesn't care. */
    maxMoonIllum: number;
};

export const TARGETS: Record<string, Target> = {
    // --- solar system ---
    moon: {
        id: "moon",
        name: "The Moon",
        kind: "moon",
        interest: "Moon",
        body: "Moon",
        blurb: "--placeholder--",
        magnitude: -12.7,
        sizeArcmin: 31,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: 5,
        maxCloudPct: 70,
        maxMoonIllum: 1,
    },
    sun: {
        id: "sun",
        name: "The Sun",
        kind: "sun",
        interest: "Sun",
        body: "Sun",
        blurb: "--placeholder--",
        magnitude: -26.7,
        sizeArcmin: 32,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: 90,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mercury: {
        id: "mercury",
        name: "Mercury",
        kind: "planet",
        interest: "Planets",
        body: "Mercury",
        blurb: "--placeholder--",
        magnitude: 0,
        minAltitudeDeg: 5,
        maxSunAltitudeDeg: -3,
        maxCloudPct: 30,
        maxMoonIllum: 1,
    },
    venus: {
        id: "venus",
        name: "Venus",
        kind: "planet",
        interest: "Planets",
        body: "Venus",
        blurb: "--placeholder--",
        magnitude: -4.2,
        minAltitudeDeg: 8,
        maxSunAltitudeDeg: 2,
        maxCloudPct: 60,
        maxMoonIllum: 1,
    },
    mars: {
        id: "mars",
        name: "Mars",
        kind: "planet",
        interest: "Planets",
        body: "Mars",
        blurb: "--placeholder--",
        magnitude: 0.7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    jupiter: {
        id: "jupiter",
        name: "Jupiter",
        kind: "planet",
        interest: "Planets",
        body: "Jupiter",
        blurb: "--placeholder--",
        magnitude: -2.2,
        sizeArcmin: 0.7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -4,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    saturn: {
        id: "saturn",
        name: "Saturn",
        kind: "planet",
        interest: "Planets",
        body: "Saturn",
        blurb: "--placeholder--",
        magnitude: 0.6,
        sizeArcmin: 0.3,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    uranus: {
        id: "uranus",
        name: "Uranus",
        kind: "planet",
        interest: "Planets",
        body: "Uranus",
        blurb: "--placeholder--",
        magnitude: 5.7,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 20,
        maxMoonIllum: 0.8,
    },
    neptune: {
        id: "neptune",
        name: "Neptune",
        kind: "planet",
        interest: "Planets",
        body: "Neptune",
        blurb: "--placeholder--",
        magnitude: 7.8,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },

    // --- stars ---
    polaris: {
        id: "polaris",
        name: "Polaris",
        kind: "star",
        interest: "Stars",
        ra: 37.95,
        dec: 89.264,
        blurb: "--placeholder--",
        magnitude: 2.0,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sirius: {
        id: "sirius",
        name: "Sirius",
        kind: "star",
        interest: "Stars",
        ra: 101.29,
        dec: -16.716,
        blurb: "--placeholder--",
        magnitude: -1.46,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    vega: {
        id: "vega",
        name: "Vega",
        kind: "star",
        interest: "Stars",
        ra: 279.23,
        dec: 38.784,
        blurb: "--placeholder--",
        magnitude: 0.03,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    betelgeuse: {
        id: "betelgeuse",
        name: "Betelgeuse",
        kind: "star",
        interest: "Stars",
        ra: 88.79,
        dec: 7.407,
        blurb: "--placeholder--",
        magnitude: 0.5,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    rigel: {
        id: "rigel",
        name: "Rigel",
        kind: "star",
        interest: "Stars",
        ra: 78.63,
        dec: -8.2,
        blurb: "--placeholder--",
        magnitude: 0.13,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    arcturus: {
        id: "arcturus",
        name: "Arcturus",
        kind: "star",
        interest: "Stars",
        ra: 213.92,
        dec: 19.18,
        blurb: "--placeholder--",
        magnitude: -0.05,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    capella: {
        id: "capella",
        name: "Capella",
        kind: "star",
        interest: "Stars",
        ra: 79.17,
        dec: 45.998,
        blurb: "--placeholder--",
        magnitude: 0.08,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    antares: {
        id: "antares",
        name: "Antares",
        kind: "star",
        interest: "Stars",
        ra: 247.35,
        dec: -26.43,
        blurb: "--placeholder--",
        magnitude: 1.06,
        minAltitudeDeg: 12,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    albireo: {
        id: "albireo",
        name: "Albireo",
        kind: "star",
        interest: "Stars",
        ra: 292.68,
        dec: 27.96,
        blurb: "--placeholder--",
        magnitude: 3.1,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mizar: {
        id: "mizar",
        name: "Mizar & Alcor",
        kind: "star",
        interest: "Stars",
        ra: 200.98,
        dec: 54.925,
        blurb: "--placeholder--",
        magnitude: 2.2,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    altair: {
        id: "altair",
        name: "Altair",
        kind: "star",
        interest: "Stars",
        ra: 297.7,
        dec: 8.87,
        blurb: "--placeholder--",
        magnitude: 0.77,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    deneb: {
        id: "deneb",
        name: "Deneb",
        kind: "star",
        interest: "Stars",
        ra: 310.36,
        dec: 45.28,
        blurb: "--placeholder--",
        magnitude: 1.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },

    // --- galaxies ---
    m31: {
        id: "m31",
        name: "M31 — Andromeda Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 10.68,
        dec: 41.269,
        blurb: "--placeholder--",
        magnitude: 3.4,
        sizeArcmin: 190,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.7,
    },
    m33: {
        id: "m33",
        name: "M33 — Triangulum Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 23.46,
        dec: 30.66,
        blurb: "--placeholder--",
        magnitude: 5.7,
        sizeArcmin: 70,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.25,
    },
    m51: {
        id: "m51",
        name: "M51 — Whirlpool Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 202.47,
        dec: 47.195,
        blurb: "--placeholder--",
        magnitude: 8.4,
        sizeArcmin: 11,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.35,
    },
    m81: {
        id: "m81",
        name: "M81 & M82 — Bode's Pair",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 148.89,
        dec: 69.065,
        blurb: "--placeholder--",
        magnitude: 6.9,
        sizeArcmin: 26,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m104: {
        id: "m104",
        name: "M104 — Sombrero Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 189.998,
        dec: -11.62,
        blurb: "--placeholder--",
        magnitude: 8.0,
        sizeArcmin: 9,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.4,
    },

    // --- nebulae ---
    m42: {
        id: "m42",
        name: "M42 — Orion Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.82,
        dec: -5.39,
        blurb: "--placeholder--",
        magnitude: 4.0,
        sizeArcmin: 85,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },
    m57: {
        id: "m57",
        name: "M57 — Ring Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 283.4,
        dec: 33.03,
        blurb: "--placeholder--",
        magnitude: 8.8,
        sizeArcmin: 1.4,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.8,
    },
    m27: {
        id: "m27",
        name: "M27 — Dumbbell Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 299.9,
        dec: 22.72,
        blurb: "--placeholder--",
        magnitude: 7.4,
        sizeArcmin: 8,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.7,
    },
    m8: {
        id: "m8",
        name: "M8 — Lagoon Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 270.9,
        dec: -24.38,
        blurb: "--placeholder--",
        magnitude: 6.0,
        sizeArcmin: 90,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m16: {
        id: "m16",
        name: "M16 — Eagle Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 274.7,
        dec: -13.79,
        blurb: "--placeholder--",
        magnitude: 6.4,
        sizeArcmin: 7,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.4,
    },
    m17: {
        id: "m17",
        name: "M17 — Omega Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 275.11,
        dec: -16.18,
        blurb: "--placeholder--",
        magnitude: 6.0,
        sizeArcmin: 11,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.6,
    },
    ngc7000: {
        id: "ngc7000",
        name: "NGC 7000 — North America Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 314.82,
        dec: 44.52,
        blurb: "--placeholder--",
        magnitude: 4.0,
        sizeArcmin: 120,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.3,
    },
    veil: {
        id: "veil",
        name: "Veil Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 311.41,
        dec: 30.72,
        blurb: "--placeholder--",
        magnitude: 7.0,
        sizeArcmin: 180,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.2,
    },

    // --- clusters ---
    m45: {
        id: "m45",
        name: "M45 — Pleiades",
        kind: "cluster",
        interest: "Stars",
        ra: 56.85,
        dec: 24.12,
        blurb: "--placeholder--",
        magnitude: 1.6,
        sizeArcmin: 110,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    m13: {
        id: "m13",
        name: "M13 — Hercules Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 250.42,
        dec: 36.46,
        blurb: "--placeholder--",
        magnitude: 5.8,
        sizeArcmin: 20,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 25,
        maxMoonIllum: 0.8,
    },
    m22: {
        id: "m22",
        name: "M22",
        kind: "cluster",
        interest: "Stars",
        ra: 279.1,
        dec: -23.9,
        blurb: "--placeholder--",
        magnitude: 5.1,
        sizeArcmin: 32,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 25,
        maxMoonIllum: 0.8,
    },
    m44: {
        id: "m44",
        name: "M44 — Beehive Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 130.1,
        dec: 19.67,
        blurb: "--placeholder--",
        magnitude: 3.7,
        sizeArcmin: 95,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.9,
    },
    m7: {
        id: "m7",
        name: "M7 — Ptolemy Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 268.46,
        dec: -34.79,
        blurb: "--placeholder--",
        magnitude: 3.3,
        sizeArcmin: 80,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },
    "double-cluster": {
        id: "double-cluster",
        name: "Double Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 34.75,
        dec: 57.13,
        blurb: "--placeholder--",
        magnitude: 4.3,
        sizeArcmin: 60,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },

    // --- stars (catalog fill) ---
    canopus: {
        id: "canopus",
        name: "Canopus",
        kind: "star",
        interest: "Stars",
        ra: 95.988,
        dec: -52.696,
        blurb: "--placeholder--",
        magnitude: -0.62,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    "alpha-centauri": {
        id: "alpha-centauri",
        name: "Alpha Centauri",
        kind: "star",
        interest: "Stars",
        ra: 219.902,
        dec: -60.834,
        blurb: "--placeholder--",
        magnitude: -0.01,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    procyon: {
        id: "procyon",
        name: "Procyon",
        kind: "star",
        interest: "Stars",
        ra: 114.825,
        dec: 5.225,
        blurb: "--placeholder--",
        magnitude: 0.4,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    achernar: {
        id: "achernar",
        name: "Achernar",
        kind: "star",
        interest: "Stars",
        ra: 24.429,
        dec: -57.237,
        blurb: "--placeholder--",
        magnitude: 0.45,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    hadar: {
        id: "hadar",
        name: "Hadar",
        kind: "star",
        interest: "Stars",
        ra: 210.956,
        dec: -60.373,
        blurb: "--placeholder--",
        magnitude: 0.61,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    acrux: {
        id: "acrux",
        name: "Acrux",
        kind: "star",
        interest: "Stars",
        ra: 186.65,
        dec: -63.099,
        blurb: "--placeholder--",
        magnitude: 1.33,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    aldebaran: {
        id: "aldebaran",
        name: "Aldebaran",
        kind: "star",
        interest: "Stars",
        ra: 68.98,
        dec: 16.509,
        blurb: "--placeholder--",
        magnitude: 0.87,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    spica: {
        id: "spica",
        name: "Spica",
        kind: "star",
        interest: "Stars",
        ra: 201.298,
        dec: -11.161,
        blurb: "--placeholder--",
        magnitude: 0.98,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    pollux: {
        id: "pollux",
        name: "Pollux",
        kind: "star",
        interest: "Stars",
        ra: 116.329,
        dec: 28.026,
        blurb: "--placeholder--",
        magnitude: 1.16,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    fomalhaut: {
        id: "fomalhaut",
        name: "Fomalhaut",
        kind: "star",
        interest: "Stars",
        ra: 344.413,
        dec: -29.622,
        blurb: "--placeholder--",
        magnitude: 1.17,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mimosa: {
        id: "mimosa",
        name: "Mimosa",
        kind: "star",
        interest: "Stars",
        ra: 191.93,
        dec: -59.689,
        blurb: "--placeholder--",
        magnitude: 1.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    regulus: {
        id: "regulus",
        name: "Regulus",
        kind: "star",
        interest: "Stars",
        ra: 152.093,
        dec: 11.967,
        blurb: "--placeholder--",
        magnitude: 1.36,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    adhara: {
        id: "adhara",
        name: "Adhara",
        kind: "star",
        interest: "Stars",
        ra: 104.656,
        dec: -28.972,
        blurb: "--placeholder--",
        magnitude: 1.5,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    castor: {
        id: "castor",
        name: "Castor",
        kind: "star",
        interest: "Stars",
        ra: 113.649,
        dec: 31.888,
        blurb: "--placeholder--",
        magnitude: 1.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    shaula: {
        id: "shaula",
        name: "Shaula",
        kind: "star",
        interest: "Stars",
        ra: 263.402,
        dec: -37.104,
        blurb: "--placeholder--",
        magnitude: 1.62,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    gacrux: {
        id: "gacrux",
        name: "Gacrux",
        kind: "star",
        interest: "Stars",
        ra: 187.791,
        dec: -57.113,
        blurb: "--placeholder--",
        magnitude: 1.59,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    bellatrix: {
        id: "bellatrix",
        name: "Bellatrix",
        kind: "star",
        interest: "Stars",
        ra: 81.283,
        dec: 6.35,
        blurb: "--placeholder--",
        magnitude: 1.64,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    elnath: {
        id: "elnath",
        name: "Elnath",
        kind: "star",
        interest: "Stars",
        ra: 81.573,
        dec: 28.607,
        blurb: "--placeholder--",
        magnitude: 1.65,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    miaplacidus: {
        id: "miaplacidus",
        name: "Miaplacidus",
        kind: "star",
        interest: "Stars",
        ra: 138.3,
        dec: -69.717,
        blurb: "--placeholder--",
        magnitude: 1.67,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnilam: {
        id: "alnilam",
        name: "Alnilam",
        kind: "star",
        interest: "Stars",
        ra: 84.053,
        dec: -1.202,
        blurb: "--placeholder--",
        magnitude: 1.69,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnair: {
        id: "alnair",
        name: "Alnair",
        kind: "star",
        interest: "Stars",
        ra: 332.058,
        dec: -46.961,
        blurb: "--placeholder--",
        magnitude: 1.73,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnitak: {
        id: "alnitak",
        name: "Alnitak",
        kind: "star",
        interest: "Stars",
        ra: 85.19,
        dec: -1.943,
        blurb: "--placeholder--",
        magnitude: 1.74,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alioth: {
        id: "alioth",
        name: "Alioth",
        kind: "star",
        interest: "Stars",
        ra: 193.507,
        dec: 55.96,
        blurb: "--placeholder--",
        magnitude: 1.76,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    dubhe: {
        id: "dubhe",
        name: "Dubhe",
        kind: "star",
        interest: "Stars",
        ra: 165.932,
        dec: 61.751,
        blurb: "--placeholder--",
        magnitude: 1.81,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mirfak: {
        id: "mirfak",
        name: "Mirfak",
        kind: "star",
        interest: "Stars",
        ra: 51.081,
        dec: 49.861,
        blurb: "--placeholder--",
        magnitude: 1.79,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    wezen: {
        id: "wezen",
        name: "Wezen",
        kind: "star",
        interest: "Stars",
        ra: 107.098,
        dec: -26.393,
        blurb: "--placeholder--",
        magnitude: 1.83,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    "gamma-velorum": {
        id: "gamma-velorum",
        name: "Gamma Velorum",
        kind: "star",
        interest: "Stars",
        ra: 122.383,
        dec: -47.337,
        blurb: "--placeholder--",
        magnitude: 1.75,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    sargas: {
        id: "sargas",
        name: "Sargas",
        kind: "star",
        interest: "Stars",
        ra: 264.33,
        dec: -42.998,
        blurb: "--placeholder--",
        magnitude: 1.86,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    "kaus-australis": {
        id: "kaus-australis",
        name: "Kaus Australis",
        kind: "star",
        interest: "Stars",
        ra: 276.043,
        dec: -34.385,
        blurb: "--placeholder--",
        magnitude: 1.79,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    avior: {
        id: "avior",
        name: "Avior",
        kind: "star",
        interest: "Stars",
        ra: 125.628,
        dec: -59.509,
        blurb: "--placeholder--",
        magnitude: 1.86,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alkaid: {
        id: "alkaid",
        name: "Alkaid",
        kind: "star",
        interest: "Stars",
        ra: 206.885,
        dec: 49.313,
        blurb: "--placeholder--",
        magnitude: 1.85,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    menkalinan: {
        id: "menkalinan",
        name: "Menkalinan",
        kind: "star",
        interest: "Stars",
        ra: 89.882,
        dec: 44.947,
        blurb: "--placeholder--",
        magnitude: 1.9,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    atria: {
        id: "atria",
        name: "Atria",
        kind: "star",
        interest: "Stars",
        ra: 252.166,
        dec: -69.028,
        blurb: "--placeholder--",
        magnitude: 1.91,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alhena: {
        id: "alhena",
        name: "Alhena",
        kind: "star",
        interest: "Stars",
        ra: 99.428,
        dec: 16.399,
        blurb: "--placeholder--",
        magnitude: 1.93,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    peacock: {
        id: "peacock",
        name: "Peacock",
        kind: "star",
        interest: "Stars",
        ra: 306.412,
        dec: -56.735,
        blurb: "--placeholder--",
        magnitude: 1.94,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alsephina: {
        id: "alsephina",
        name: "Alsephina",
        kind: "star",
        interest: "Stars",
        ra: 131.176,
        dec: -54.709,
        blurb: "--placeholder--",
        magnitude: 1.99,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mirzam: {
        id: "mirzam",
        name: "Mirzam",
        kind: "star",
        interest: "Stars",
        ra: 95.675,
        dec: -17.956,
        blurb: "--placeholder--",
        magnitude: 1.98,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alphard: {
        id: "alphard",
        name: "Alphard",
        kind: "star",
        interest: "Stars",
        ra: 141.897,
        dec: -8.659,
        blurb: "--placeholder--",
        magnitude: 1.99,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    hamal: {
        id: "hamal",
        name: "Hamal",
        kind: "star",
        interest: "Stars",
        ra: 31.793,
        dec: 23.462,
        blurb: "--placeholder--",
        magnitude: 2.01,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    diphda: {
        id: "diphda",
        name: "Diphda",
        kind: "star",
        interest: "Stars",
        ra: 10.897,
        dec: -17.987,
        blurb: "--placeholder--",
        magnitude: 2.04,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    nunki: {
        id: "nunki",
        name: "Nunki",
        kind: "star",
        interest: "Stars",
        ra: 283.816,
        dec: -26.297,
        blurb: "--placeholder--",
        magnitude: 2.05,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    menkent: {
        id: "menkent",
        name: "Menkent",
        kind: "star",
        interest: "Stars",
        ra: 211.671,
        dec: -36.37,
        blurb: "--placeholder--",
        magnitude: 2.06,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alpheratz: {
        id: "alpheratz",
        name: "Alpheratz",
        kind: "star",
        interest: "Stars",
        ra: 2.097,
        dec: 29.09,
        blurb: "--placeholder--",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mirach: {
        id: "mirach",
        name: "Mirach",
        kind: "star",
        interest: "Stars",
        ra: 17.433,
        dec: 35.621,
        blurb: "--placeholder--",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    rasalhague: {
        id: "rasalhague",
        name: "Rasalhague",
        kind: "star",
        interest: "Stars",
        ra: 263.734,
        dec: 12.56,
        blurb: "--placeholder--",
        magnitude: 2.08,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    algieba: {
        id: "algieba",
        name: "Algieba",
        kind: "star",
        interest: "Stars",
        ra: 154.993,
        dec: 19.841,
        blurb: "--placeholder--",
        magnitude: 2.61,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    kochab: {
        id: "kochab",
        name: "Kochab",
        kind: "star",
        interest: "Stars",
        ra: 222.676,
        dec: 74.156,
        blurb: "--placeholder--",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    saiph: {
        id: "saiph",
        name: "Saiph",
        kind: "star",
        interest: "Stars",
        ra: 86.939,
        dec: -9.67,
        blurb: "--placeholder--",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    denebola: {
        id: "denebola",
        name: "Denebola",
        kind: "star",
        interest: "Stars",
        ra: 177.265,
        dec: 14.572,
        blurb: "--placeholder--",
        magnitude: 2.14,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    algol: {
        id: "algol",
        name: "Algol",
        kind: "star",
        interest: "Stars",
        ra: 47.042,
        dec: 40.956,
        blurb: "--placeholder--",
        magnitude: 2.09,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    tiaki: {
        id: "tiaki",
        name: "Tiaki",
        kind: "star",
        interest: "Stars",
        ra: 340.667,
        dec: -46.885,
        blurb: "--placeholder--",
        magnitude: 2.12,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    muhlifain: {
        id: "muhlifain",
        name: "Muhlifain",
        kind: "star",
        interest: "Stars",
        ra: 190.379,
        dec: -48.96,
        blurb: "--placeholder--",
        magnitude: 2.2,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aspidiske: {
        id: "aspidiske",
        name: "Aspidiske",
        kind: "star",
        interest: "Stars",
        ra: 139.273,
        dec: -59.275,
        blurb: "--placeholder--",
        magnitude: 2.21,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    suhail: {
        id: "suhail",
        name: "Suhail",
        kind: "star",
        interest: "Stars",
        ra: 136.999,
        dec: -43.433,
        blurb: "--placeholder--",
        magnitude: 2.23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alphecca: {
        id: "alphecca",
        name: "Alphecca",
        kind: "star",
        interest: "Stars",
        ra: 233.672,
        dec: 26.715,
        blurb: "--placeholder--",
        magnitude: 2.22,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mintaka: {
        id: "mintaka",
        name: "Mintaka",
        kind: "star",
        interest: "Stars",
        ra: 83.002,
        dec: -0.299,
        blurb: "--placeholder--",
        magnitude: 2.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sadr: {
        id: "sadr",
        name: "Sadr",
        kind: "star",
        interest: "Stars",
        ra: 305.557,
        dec: 40.257,
        blurb: "--placeholder--",
        magnitude: 2.23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    eltanin: {
        id: "eltanin",
        name: "Eltanin",
        kind: "star",
        interest: "Stars",
        ra: 269.152,
        dec: 51.489,
        blurb: "--placeholder--",
        magnitude: 2.24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    schedar: {
        id: "schedar",
        name: "Schedar",
        kind: "star",
        interest: "Stars",
        ra: 10.127,
        dec: 56.537,
        blurb: "--placeholder--",
        magnitude: 2.24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    naos: {
        id: "naos",
        name: "Naos",
        kind: "star",
        interest: "Stars",
        ra: 120.896,
        dec: -40.003,
        blurb: "--placeholder--",
        magnitude: 2.21,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    almach: {
        id: "almach",
        name: "Almach",
        kind: "star",
        interest: "Stars",
        ra: 30.975,
        dec: 42.33,
        blurb: "--placeholder--",
        magnitude: 2.1,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    caph: {
        id: "caph",
        name: "Caph",
        kind: "star",
        interest: "Stars",
        ra: 2.295,
        dec: 59.15,
        blurb: "--placeholder--",
        magnitude: 2.28,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    izar: {
        id: "izar",
        name: "Izar",
        kind: "star",
        interest: "Stars",
        ra: 221.247,
        dec: 27.074,
        blurb: "--placeholder--",
        magnitude: 2.35,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    uridim: {
        id: "uridim",
        name: "Uridim",
        kind: "star",
        interest: "Stars",
        ra: 230.671,
        dec: -44.684,
        blurb: "--placeholder--",
        magnitude: 3.37,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 35,
        maxMoonIllum: 0.9,
    },
    "epsilon-centauri": {
        id: "epsilon-centauri",
        name: "Epsilon Centauri",
        kind: "star",
        interest: "Stars",
        ra: 204.972,
        dec: -53.466,
        blurb: "--placeholder--",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    dschubba: {
        id: "dschubba",
        name: "Dschubba",
        kind: "star",
        interest: "Stars",
        ra: 240.083,
        dec: -22.622,
        blurb: "--placeholder--",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    larawag: {
        id: "larawag",
        name: "Larawag",
        kind: "star",
        interest: "Stars",
        ra: 252.541,
        dec: -34.293,
        blurb: "--placeholder--",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "eta-centauri": {
        id: "eta-centauri",
        name: "Eta Centauri",
        kind: "star",
        interest: "Stars",
        ra: 218.877,
        dec: -42.158,
        blurb: "--placeholder--",
        magnitude: 2.33,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    merak: {
        id: "merak",
        name: "Merak",
        kind: "star",
        interest: "Stars",
        ra: 165.46,
        dec: 56.382,
        blurb: "--placeholder--",
        magnitude: 2.34,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    ankaa: {
        id: "ankaa",
        name: "Ankaa",
        kind: "star",
        interest: "Stars",
        ra: 6.571,
        dec: -42.306,
        blurb: "--placeholder--",
        magnitude: 2.4,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    girtab: {
        id: "girtab",
        name: "Girtab",
        kind: "star",
        interest: "Stars",
        ra: 265.622,
        dec: -39.03,
        blurb: "--placeholder--",
        magnitude: 2.41,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    enif: {
        id: "enif",
        name: "Enif",
        kind: "star",
        interest: "Stars",
        ra: 326.046,
        dec: 9.875,
        blurb: "--placeholder--",
        magnitude: 2.38,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    scheat: {
        id: "scheat",
        name: "Scheat",
        kind: "star",
        interest: "Stars",
        ra: 345.944,
        dec: 28.083,
        blurb: "--placeholder--",
        magnitude: 2.44,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sabik: {
        id: "sabik",
        name: "Sabik",
        kind: "star",
        interest: "Stars",
        ra: 257.595,
        dec: -15.725,
        blurb: "--placeholder--",
        magnitude: 2.43,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    phecda: {
        id: "phecda",
        name: "Phecda",
        kind: "star",
        interest: "Stars",
        ra: 178.458,
        dec: 53.695,
        blurb: "--placeholder--",
        magnitude: 2.41,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aludra: {
        id: "aludra",
        name: "Aludra",
        kind: "star",
        interest: "Stars",
        ra: 111.024,
        dec: -29.303,
        blurb: "--placeholder--",
        magnitude: 2.45,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alderamin: {
        id: "alderamin",
        name: "Alderamin",
        kind: "star",
        interest: "Stars",
        ra: 319.645,
        dec: 62.586,
        blurb: "--placeholder--",
        magnitude: 2.45,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    markeb: {
        id: "markeb",
        name: "Markeb",
        kind: "star",
        interest: "Stars",
        ra: 140.528,
        dec: -55.011,
        blurb: "--placeholder--",
        magnitude: 2.47,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    tiansi: {
        id: "tiansi",
        name: "Tiansi (Gamma Cassiopeiae)",
        kind: "star",
        interest: "Stars",
        ra: 14.177,
        dec: 60.717,
        blurb: "--placeholder--",
        magnitude: 2.47,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    markab: {
        id: "markab",
        name: "Markab",
        kind: "star",
        interest: "Stars",
        ra: 346.19,
        dec: 15.205,
        blurb: "--placeholder--",
        magnitude: 2.49,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aljanah: {
        id: "aljanah",
        name: "Aljanah",
        kind: "star",
        interest: "Stars",
        ra: 311.553,
        dec: 33.97,
        blurb: "--placeholder--",
        magnitude: 2.48,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    acrab: {
        id: "acrab",
        name: "Acrab",
        kind: "star",
        interest: "Stars",
        ra: 241.359,
        dec: -19.805,
        blurb: "--placeholder--",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    muliphein: {
        id: "muliphein",
        name: "Muliphein",
        kind: "star",
        interest: "Stars",
        ra: 105.94,
        dec: -15.633,
        blurb: "--placeholder--",
        magnitude: 4.11,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.8,
    },
    tureis: {
        id: "tureis",
        name: "Tureis",
        kind: "star",
        interest: "Stars",
        ra: 121.886,
        dec: -24.304,
        blurb: "--placeholder--",
        magnitude: 2.83,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "zeta-ophiuchi": {
        id: "zeta-ophiuchi",
        name: "Zeta Ophiuchi",
        kind: "star",
        interest: "Stars",
        ra: 249.29,
        dec: -10.567,
        blurb: "--placeholder--",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    menkar: {
        id: "menkar",
        name: "Menkar",
        kind: "star",
        interest: "Stars",
        ra: 45.57,
        dec: 4.09,
        blurb: "--placeholder--",
        magnitude: 2.54,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    zosma: {
        id: "zosma",
        name: "Zosma",
        kind: "star",
        interest: "Stars",
        ra: 168.527,
        dec: 20.524,
        blurb: "--placeholder--",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "delta-centauri": {
        id: "delta-centauri",
        name: "Delta Centauri",
        kind: "star",
        interest: "Stars",
        ra: 182.09,
        dec: -50.723,
        blurb: "--placeholder--",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    arneb: {
        id: "arneb",
        name: "Arneb",
        kind: "star",
        interest: "Stars",
        ra: 83.183,
        dec: -17.822,
        blurb: "--placeholder--",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    gienah: {
        id: "gienah",
        name: "Gienah",
        kind: "star",
        interest: "Stars",
        ra: 183.952,
        dec: -17.542,
        blurb: "--placeholder--",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },

    // --- galaxies (catalog fill) ---
    m32: {
        id: "m32",
        name: "M32",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 10.674,
        dec: 40.865,
        blurb: "--placeholder--",
        magnitude: 8.1,
        sizeArcmin: 7.6,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.65,
    },
    m49: {
        id: "m49",
        name: "M49",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 187.445,
        dec: 8.001,
        blurb: "--placeholder--",
        magnitude: 8.4,
        sizeArcmin: 10.2,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m58: {
        id: "m58",
        name: "M58",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 189.431,
        dec: 11.818,
        blurb: "--placeholder--",
        magnitude: 9.7,
        sizeArcmin: 5.9,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m59: {
        id: "m59",
        name: "M59",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 190.51,
        dec: 11.647,
        blurb: "--placeholder--",
        magnitude: 9.6,
        sizeArcmin: 5.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m60: {
        id: "m60",
        name: "M60",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 190.915,
        dec: 11.553,
        blurb: "--placeholder--",
        magnitude: 8.8,
        sizeArcmin: 7.4,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m61: {
        id: "m61",
        name: "M61",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 185.479,
        dec: 4.474,
        blurb: "--placeholder--",
        magnitude: 9.7,
        sizeArcmin: 6.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m63: {
        id: "m63",
        name: "M63 — Sunflower Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 198.955,
        dec: 42.029,
        blurb: "--placeholder--",
        magnitude: 8.6,
        sizeArcmin: 12.6,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m64: {
        id: "m64",
        name: "M64 — Black Eye Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 194.182,
        dec: 21.683,
        blurb: "--placeholder--",
        magnitude: 8.5,
        sizeArcmin: 10.7,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m65: {
        id: "m65",
        name: "M65",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 169.733,
        dec: 13.092,
        blurb: "--placeholder--",
        magnitude: 9.3,
        sizeArcmin: 8.7,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m66: {
        id: "m66",
        name: "M66",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 170.063,
        dec: 12.992,
        blurb: "--placeholder--",
        magnitude: 8.9,
        sizeArcmin: 9.1,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m74: {
        id: "m74",
        name: "M74 — Phantom Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 24.174,
        dec: 15.784,
        blurb: "--placeholder--",
        magnitude: 9.4,
        sizeArcmin: 10.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m77: {
        id: "m77",
        name: "M77 — Squid Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 40.67,
        dec: -0.013,
        blurb: "--placeholder--",
        magnitude: 8.9,
        sizeArcmin: 7.1,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m83: {
        id: "m83",
        name: "M83 — Southern Pinwheel Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 204.254,
        dec: -29.866,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 12.9,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.4,
    },
    m84: {
        id: "m84",
        name: "M84",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 186.265,
        dec: 12.887,
        blurb: "--placeholder--",
        magnitude: 9.1,
        sizeArcmin: 6.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m85: {
        id: "m85",
        name: "M85",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 186.35,
        dec: 18.191,
        blurb: "--placeholder--",
        magnitude: 9.1,
        sizeArcmin: 7.1,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m86: {
        id: "m86",
        name: "M86",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 186.549,
        dec: 12.946,
        blurb: "--placeholder--",
        magnitude: 8.9,
        sizeArcmin: 8.9,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m87: {
        id: "m87",
        name: "M87 — Virgo A",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 187.706,
        dec: 12.391,
        blurb: "--placeholder--",
        magnitude: 8.6,
        sizeArcmin: 7.2,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m88: {
        id: "m88",
        name: "M88",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 187.997,
        dec: 14.421,
        blurb: "--placeholder--",
        magnitude: 9.6,
        sizeArcmin: 6.9,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m89: {
        id: "m89",
        name: "M89",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 188.916,
        dec: 12.556,
        blurb: "--placeholder--",
        magnitude: 9.8,
        sizeArcmin: 5.1,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m90: {
        id: "m90",
        name: "M90",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 189.208,
        dec: 13.163,
        blurb: "--placeholder--",
        magnitude: 9.5,
        sizeArcmin: 9.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m91: {
        id: "m91",
        name: "M91",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 188.86,
        dec: 14.496,
        blurb: "--placeholder--",
        magnitude: 10.2,
        sizeArcmin: 5.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m94: {
        id: "m94",
        name: "M94",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 192.721,
        dec: 41.121,
        blurb: "--placeholder--",
        magnitude: 8.2,
        sizeArcmin: 11.2,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m95: {
        id: "m95",
        name: "M95",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 160.99,
        dec: 11.704,
        blurb: "--placeholder--",
        magnitude: 9.7,
        sizeArcmin: 3.1,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.65,
    },
    m96: {
        id: "m96",
        name: "M96",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 161.69,
        dec: 11.82,
        blurb: "--placeholder--",
        magnitude: 9.2,
        sizeArcmin: 7.6,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m98: {
        id: "m98",
        name: "M98",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 183.451,
        dec: 14.901,
        blurb: "--placeholder--",
        magnitude: 10.1,
        sizeArcmin: 9.8,
        minAltitudeDeg: 29,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m99: {
        id: "m99",
        name: "M99 — St. Catherine's Wheel",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 184.707,
        dec: 14.416,
        blurb: "--placeholder--",
        magnitude: 9.9,
        sizeArcmin: 5.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m100: {
        id: "m100",
        name: "M100 — Mirror Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 185.729,
        dec: 15.822,
        blurb: "--placeholder--",
        magnitude: 9.3,
        sizeArcmin: 7.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m101: {
        id: "m101",
        name: "M101 — Pinwheel Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 210.803,
        dec: 54.349,
        blurb: "--placeholder--",
        magnitude: 7.9,
        sizeArcmin: 28.8,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.4,
    },
    m102: {
        id: "m102",
        name: "M102 — Spindle Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 226.623,
        dec: 55.763,
        blurb: "--placeholder--",
        magnitude: 9.9,
        sizeArcmin: 4.7,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m105: {
        id: "m105",
        name: "M105",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 161.957,
        dec: 12.582,
        blurb: "--placeholder--",
        magnitude: 9.3,
        sizeArcmin: 5.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m106: {
        id: "m106",
        name: "M106",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 184.74,
        dec: 47.304,
        blurb: "--placeholder--",
        magnitude: 8.4,
        sizeArcmin: 18.6,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m108: {
        id: "m108",
        name: "M108 — Surfboard Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 167.879,
        dec: 55.674,
        blurb: "--placeholder--",
        magnitude: 10.0,
        sizeArcmin: 8.7,
        minAltitudeDeg: 29,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m109: {
        id: "m109",
        name: "M109 — Vacuum Cleaner Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 179.4,
        dec: 53.374,
        blurb: "--placeholder--",
        magnitude: 9.8,
        sizeArcmin: 7.6,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m110: {
        id: "m110",
        name: "M110",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 10.092,
        dec: 41.685,
        blurb: "--placeholder--",
        magnitude: 8.5,
        sizeArcmin: 21.9,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },

    // --- nebulae (catalog fill) ---
    m1: {
        id: "m1",
        name: "M1 — Crab Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.633,
        dec: 22.015,
        blurb: "--placeholder--",
        magnitude: 8.4,
        sizeArcmin: 7,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m20: {
        id: "m20",
        name: "M20 — Trifid Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 270.596,
        dec: -23.03,
        blurb: "--placeholder--",
        magnitude: 6.3,
        sizeArcmin: 28,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m43: {
        id: "m43",
        name: "M43 — De Mairan's Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.9,
        dec: -5.267,
        blurb: "--placeholder--",
        magnitude: 9.0,
        sizeArcmin: 20,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.55,
    },
    m76: {
        id: "m76",
        name: "M76 — Little Dumbbell Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 25.6,
        dec: 51.575,
        blurb: "--placeholder--",
        magnitude: 10.1,
        sizeArcmin: 2.7,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.65,
    },
    m78: {
        id: "m78",
        name: "M78",
        kind: "nebula",
        interest: "Nebulae",
        ra: 86.695,
        dec: 0.014,
        blurb: "--placeholder--",
        magnitude: 8.3,
        sizeArcmin: 8,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m97: {
        id: "m97",
        name: "M97 — Owl Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 168.699,
        dec: 55.019,
        blurb: "--placeholder--",
        magnitude: 9.9,
        sizeArcmin: 3.4,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.65,
    },
    ngc6543: {
        id: "ngc6543",
        name: "NGC 6543 — Cat's Eye Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 269.639,
        dec: 66.633,
        blurb: "--placeholder--",
        magnitude: 8.1,
        sizeArcmin: 0.3,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.75,
    },
    ngc7635: {
        id: "ngc7635",
        name: "NGC 7635 — Bubble Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 350.201,
        dec: 61.202,
        blurb: "--placeholder--",
        magnitude: 10.0,
        sizeArcmin: 15,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.55,
    },
    ngc7293: {
        id: "ngc7293",
        name: "NGC 7293 — Helix Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 337.411,
        dec: -20.837,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 25,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    ngc3132: {
        id: "ngc3132",
        name: "NGC 3132 — Southern Ring Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 151.757,
        dec: -40.436,
        blurb: "--placeholder--",
        magnitude: 9.9,
        sizeArcmin: 1,
        minAltitudeDeg: 26,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.7,
    },
    ngc3372: {
        id: "ngc3372",
        name: "NGC 3372 — Carina Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 161.285,
        dec: -59.868,
        blurb: "--placeholder--",
        magnitude: 1.0,
        sizeArcmin: 120,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    ngc2174: {
        id: "ngc2174",
        name: "NGC 2174 — Monkey Head Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 92.425,
        dec: 20.5,
        blurb: "--placeholder--",
        magnitude: 6.8,
        sizeArcmin: 40,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    ngc2313: {
        id: "ngc2313",
        name: "NGC 2313",
        kind: "nebula",
        interest: "Nebulae",
        ra: 104.829,
        dec: -7.982,
        blurb: "--placeholder--",
        magnitude: 14.2,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },

    // --- clusters (catalog fill) ---
    m2: {
        id: "m2",
        name: "M2",
        kind: "cluster",
        interest: "Stars",
        ra: 323.363,
        dec: -0.823,
        blurb: "--placeholder--",
        magnitude: 6.5,
        sizeArcmin: 16,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m3: {
        id: "m3",
        name: "M3",
        kind: "cluster",
        interest: "Stars",
        ra: 205.548,
        dec: 28.377,
        blurb: "--placeholder--",
        magnitude: 6.2,
        sizeArcmin: 18,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m4: {
        id: "m4",
        name: "M4 — Spider Globular Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 245.897,
        dec: -26.526,
        blurb: "--placeholder--",
        magnitude: 5.6,
        sizeArcmin: 26,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m5: {
        id: "m5",
        name: "M5 — Rose Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 229.638,
        dec: 2.081,
        blurb: "--placeholder--",
        magnitude: 5.6,
        sizeArcmin: 23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m6: {
        id: "m6",
        name: "M6 — Butterfly Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 265.025,
        dec: -32.217,
        blurb: "--placeholder--",
        magnitude: 4.2,
        sizeArcmin: 25,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m9: {
        id: "m9",
        name: "M9",
        kind: "cluster",
        interest: "Stars",
        ra: 259.799,
        dec: -18.516,
        blurb: "--placeholder--",
        magnitude: 7.7,
        sizeArcmin: 9.3,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m10: {
        id: "m10",
        name: "M10",
        kind: "cluster",
        interest: "Stars",
        ra: 254.287,
        dec: -4.1,
        blurb: "--placeholder--",
        magnitude: 6.6,
        sizeArcmin: 20,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m11: {
        id: "m11",
        name: "M11 — Wild Duck Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 282.775,
        dec: -6.267,
        blurb: "--placeholder--",
        magnitude: 5.8,
        sizeArcmin: 22.8,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m12: {
        id: "m12",
        name: "M12",
        kind: "cluster",
        interest: "Stars",
        ra: 251.809,
        dec: -1.949,
        blurb: "--placeholder--",
        magnitude: 6.7,
        sizeArcmin: 16,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m14: {
        id: "m14",
        name: "M14",
        kind: "cluster",
        interest: "Stars",
        ra: 264.401,
        dec: -3.246,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 11,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m15: {
        id: "m15",
        name: "M15 — Great Pegasus Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 322.493,
        dec: 12.167,
        blurb: "--placeholder--",
        magnitude: 6.2,
        sizeArcmin: 18,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m18: {
        id: "m18",
        name: "M18 — Black Swan Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 274.975,
        dec: -17.133,
        blurb: "--placeholder--",
        magnitude: 7.5,
        sizeArcmin: 9.8,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m19: {
        id: "m19",
        name: "M19",
        kind: "cluster",
        interest: "Stars",
        ra: 255.657,
        dec: -26.268,
        blurb: "--placeholder--",
        magnitude: 6.8,
        sizeArcmin: 17,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m21: {
        id: "m21",
        name: "M21 — Webb's Cross Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 271.15,
        dec: -22.5,
        blurb: "--placeholder--",
        magnitude: 6.5,
        sizeArcmin: 14,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m23: {
        id: "m23",
        name: "M23",
        kind: "cluster",
        interest: "Stars",
        ra: 269.2,
        dec: -19.017,
        blurb: "--placeholder--",
        magnitude: 5.5,
        sizeArcmin: 35,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m25: {
        id: "m25",
        name: "M25",
        kind: "cluster",
        interest: "Stars",
        ra: 277.9,
        dec: -19.25,
        blurb: "--placeholder--",
        magnitude: 4.6,
        sizeArcmin: 36,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m26: {
        id: "m26",
        name: "M26",
        kind: "cluster",
        interest: "Stars",
        ra: 281.3,
        dec: -9.4,
        blurb: "--placeholder--",
        magnitude: 8.0,
        sizeArcmin: 14,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m28: {
        id: "m28",
        name: "M28",
        kind: "cluster",
        interest: "Stars",
        ra: 276.137,
        dec: -24.87,
        blurb: "--placeholder--",
        magnitude: 6.8,
        sizeArcmin: 11.2,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m29: {
        id: "m29",
        name: "M29 — Cooling Tower Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 305.983,
        dec: 38.523,
        blurb: "--placeholder--",
        magnitude: 7.1,
        sizeArcmin: 7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m30: {
        id: "m30",
        name: "M30 — Jellyfish Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 325.092,
        dec: -23.18,
        blurb: "--placeholder--",
        magnitude: 7.2,
        sizeArcmin: 12,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m34: {
        id: "m34",
        name: "M34 — Spiral Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 40.525,
        dec: 42.767,
        blurb: "--placeholder--",
        magnitude: 5.5,
        sizeArcmin: 35,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m35: {
        id: "m35",
        name: "M35 — Shoe-Buckle Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 92.275,
        dec: 24.35,
        blurb: "--placeholder--",
        magnitude: 5.3,
        sizeArcmin: 28,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m36: {
        id: "m36",
        name: "M36 — Pinwheel Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 84.05,
        dec: 34.134,
        blurb: "--placeholder--",
        magnitude: 6.3,
        sizeArcmin: 12,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m37: {
        id: "m37",
        name: "M37 — Salt and Pepper Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 88.075,
        dec: 32.551,
        blurb: "--placeholder--",
        magnitude: 6.2,
        sizeArcmin: 24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m38: {
        id: "m38",
        name: "M38 — Starfish Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 82.175,
        dec: 35.855,
        blurb: "--placeholder--",
        magnitude: 7.4,
        sizeArcmin: 21,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m39: {
        id: "m39",
        name: "M39 — Pyramid Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 322.925,
        dec: 48.433,
        blurb: "--placeholder--",
        magnitude: 4.6,
        sizeArcmin: 29,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m41: {
        id: "m41",
        name: "M41 — Little Beehive Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 101.5,
        dec: -20.767,
        blurb: "--placeholder--",
        magnitude: 4.5,
        sizeArcmin: 38,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m46: {
        id: "m46",
        name: "M46",
        kind: "cluster",
        interest: "Stars",
        ra: 115.45,
        dec: -14.817,
        blurb: "--placeholder--",
        magnitude: 6.0,
        sizeArcmin: 22.8,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m47: {
        id: "m47",
        name: "M47",
        kind: "cluster",
        interest: "Stars",
        ra: 114.15,
        dec: -14.5,
        blurb: "--placeholder--",
        magnitude: 4.4,
        sizeArcmin: 30,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m48: {
        id: "m48",
        name: "M48",
        kind: "cluster",
        interest: "Stars",
        ra: 123.425,
        dec: -5.75,
        blurb: "--placeholder--",
        magnitude: 5.5,
        sizeArcmin: 30,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m50: {
        id: "m50",
        name: "M50 — Heart-Shaped Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 105.8,
        dec: -8.333,
        blurb: "--placeholder--",
        magnitude: 5.9,
        sizeArcmin: 16,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m52: {
        id: "m52",
        name: "M52 — Scorpion Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 351.05,
        dec: 61.583,
        blurb: "--placeholder--",
        magnitude: 7.3,
        sizeArcmin: 13,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m53: {
        id: "m53",
        name: "M53",
        kind: "cluster",
        interest: "Stars",
        ra: 198.23,
        dec: 18.168,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 13,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m54: {
        id: "m54",
        name: "M54",
        kind: "cluster",
        interest: "Stars",
        ra: 283.764,
        dec: -30.48,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 12,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m55: {
        id: "m55",
        name: "M55 — Specter Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 294.999,
        dec: -30.965,
        blurb: "--placeholder--",
        magnitude: 6.3,
        sizeArcmin: 19,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m56: {
        id: "m56",
        name: "M56",
        kind: "cluster",
        interest: "Stars",
        ra: 289.148,
        dec: 30.184,
        blurb: "--placeholder--",
        magnitude: 8.3,
        sizeArcmin: 8.8,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m62: {
        id: "m62",
        name: "M62 — Flickering Globular",
        kind: "cluster",
        interest: "Stars",
        ra: 255.303,
        dec: -30.112,
        blurb: "--placeholder--",
        magnitude: 6.5,
        sizeArcmin: 15,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m67: {
        id: "m67",
        name: "M67 — King Cobra Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 132.825,
        dec: 11.817,
        blurb: "--placeholder--",
        magnitude: 6.1,
        sizeArcmin: 30,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m68: {
        id: "m68",
        name: "M68",
        kind: "cluster",
        interest: "Stars",
        ra: 189.867,
        dec: -26.744,
        blurb: "--placeholder--",
        magnitude: 7.8,
        sizeArcmin: 11,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m69: {
        id: "m69",
        name: "M69",
        kind: "cluster",
        interest: "Stars",
        ra: 277.896,
        dec: -32.348,
        blurb: "--placeholder--",
        magnitude: 7.6,
        sizeArcmin: 10.8,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m70: {
        id: "m70",
        name: "M70",
        kind: "cluster",
        interest: "Stars",
        ra: 280.803,
        dec: -32.292,
        blurb: "--placeholder--",
        magnitude: 7.9,
        sizeArcmin: 8,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m71: {
        id: "m71",
        name: "M71 — Angelfish Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 298.444,
        dec: 18.779,
        blurb: "--placeholder--",
        magnitude: 8.2,
        sizeArcmin: 7.2,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m72: {
        id: "m72",
        name: "M72",
        kind: "cluster",
        interest: "Stars",
        ra: 313.365,
        dec: -12.537,
        blurb: "--placeholder--",
        magnitude: 9.3,
        sizeArcmin: 6.6,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m75: {
        id: "m75",
        name: "M75",
        kind: "cluster",
        interest: "Stars",
        ra: 301.52,
        dec: -21.921,
        blurb: "--placeholder--",
        magnitude: 8.5,
        sizeArcmin: 6.8,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m79: {
        id: "m79",
        name: "M79",
        kind: "cluster",
        interest: "Stars",
        ra: 81.044,
        dec: -24.524,
        blurb: "--placeholder--",
        magnitude: 7.7,
        sizeArcmin: 8.7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m80: {
        id: "m80",
        name: "M80",
        kind: "cluster",
        interest: "Stars",
        ra: 244.26,
        dec: -22.976,
        blurb: "--placeholder--",
        magnitude: 7.3,
        sizeArcmin: 10,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m92: {
        id: "m92",
        name: "M92",
        kind: "cluster",
        interest: "Stars",
        ra: 259.281,
        dec: 43.136,
        blurb: "--placeholder--",
        magnitude: 6.4,
        sizeArcmin: 14,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m93: {
        id: "m93",
        name: "M93 — Critter Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 116.15,
        dec: -23.867,
        blurb: "--placeholder--",
        magnitude: 6.0,
        sizeArcmin: 10,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m103: {
        id: "m103",
        name: "M103",
        kind: "cluster",
        interest: "Stars",
        ra: 23.3,
        dec: 60.7,
        blurb: "--placeholder--",
        magnitude: 7.4,
        sizeArcmin: 6,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m107: {
        id: "m107",
        name: "M107 — Crucifix Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 248.133,
        dec: -13.054,
        blurb: "--placeholder--",
        magnitude: 7.9,
        sizeArcmin: 10,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
};

export const ICONS: Record<Target["kind"], IconName> = {
    planet: "planet",
    moon: "moon",
    sun: "sun",
    star: "astroid",
    galaxy: "orbit",
    nebula: "nebula",
    cluster: "astroid",
};
