import type { IconName } from "@/components/icon";
import type { Body } from "@/lib/sky";




















































































































































/**
 * minAltitudeDeg: https://en.wikipedia.org/wiki/Air_mass_(astronomy)#cite_ref-3:~:text=Pickering%20(2002)%20developed
 * maxSunAltitudeDeg: https://www.hnsky.org/sqm_twilight.htm
 * maxCloudPct: https://www.cleardarksky.com/c/DSPNMkey.html
 * maxMoonIllum: https://articles.adsabs.harvard.edu/pdf/1991PASP..103.1033K
 */

export type Target = {
    id: string;
    name: string;
    kind: "planet" | "moon" | "sun" | "star" | "galaxy" | "nebula" | "cluster";
    interest: "Planets" | "Moon" | "Sun" | "Stars" | "Galaxies" | "Nebulae";
    blurb: string;
    magnitude: number;
    sizeArcmin?: number;
    /** fixed objects: J2000 right ascension / declination, degrees */
    ra?: number;
    dec?: number;
    /** moving objects: run through the ephemeris instead of ra/dec */
    body?: Body;

    minAltitudeDeg: number;
    /** How dark it has to be: 0 sunset, -6 civil, -12 nautical, -18 astronomical dusk. */
    maxSunAltitudeDeg: number;
    /** Weather requirement: cloud cover percentage this can tolerate. */
    maxCloudPct: number;
    /** Moonlight this can tolerate, 0..1 lit fraction. 1 = doesn't care. */
    maxMoonIllum: number;
};

export const TARGETS: Record<string, Target> = {
    // --- solar system ---
    moon: {
        id: "moon",
        name: "The Moon",
        kind: "moon",
        interest: "Moon",
        body: "Moon",
        blurb: "Known natural satellite of Earth, tidally locked; synodic orbital period 29.5 days.",
        magnitude: -12.7,
        sizeArcmin: 31,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: 5,
        maxCloudPct: 70,
        maxMoonIllum: 1,
    },
    sun: {
        id: "sun",
        name: "The Sun",
        kind: "sun",
        interest: "Sun",
        body: "Sun",
        blurb: "Main-sequence spectral type G star, approximate center of the Solar System",
        magnitude: -26.7,
        sizeArcmin: 32,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: 90,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mercury: {
        id: "mercury",
        name: "Mercury",
        kind: "planet",
        interest: "Planets",
        body: "Mercury",
        blurb: "First planet, terrestrial; 0.38 R⊕, 0.055 M⊕, sidereal orbital period 88 days.",
        magnitude: 0,
        minAltitudeDeg: 5,
        maxSunAltitudeDeg: -3,
        maxCloudPct: 30,
        maxMoonIllum: 1,
    },
    venus: {
        id: "venus",
        name: "Venus",
        kind: "planet",
        interest: "Planets",
        body: "Venus",
        blurb: "Second planet, terrestrial; 0.95 R⊕, 0.815 M⊕, sidereal orbital period 225 days.",
        magnitude: -4.2,
        minAltitudeDeg: 8,
        maxSunAltitudeDeg: 2,
        maxCloudPct: 60,
        maxMoonIllum: 1,
    },
    mars: {
        id: "mars",
        name: "Mars",
        kind: "planet",
        interest: "Planets",
        body: "Mars",
        blurb: "Fourth planet, terrestrial; 0.53 R⊕, 0.107 M⊕, sidereal orbital period 687 days; two known natural satellites.",
        magnitude: 0.7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    jupiter: {
        id: "jupiter",
        name: "Jupiter",
        kind: "planet",
        interest: "Planets",
        body: "Jupiter",
        blurb: "Fifth planet, gas giant; 11 R⊕, 318 M⊕, sidereal orbital period 11.9 years; 115 known natural satellites.",
        magnitude: -2.2,
        sizeArcmin: 0.7,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -4,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    saturn: {
        id: "saturn",
        name: "Saturn",
        kind: "planet",
        interest: "Planets",
        body: "Saturn",
        blurb: "Sixth planet, gas giant; 9 R⊕, 95 M⊕, sidereal orbital period 29.4 years; 293 known natural satellites.",
        magnitude: 0.6,
        sizeArcmin: 0.3,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    uranus: {
        id: "uranus",
        name: "Uranus",
        kind: "planet",
        interest: "Planets",
        body: "Uranus",
        blurb: "Seventh planet, ice giant; 4 R⊕, 14.5 M⊕, sidereal orbital period 84.0 years; 29 known natural satellites.",
        magnitude: 5.7,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 20,
        maxMoonIllum: 0.8,
    },
    neptune: {
        id: "neptune",
        name: "Neptune",
        kind: "planet",
        interest: "Planets",
        body: "Neptune",
        blurb: "Eighth planet, ice giant; 4 R⊕, 17.1 M⊕, sidereal orbital period 164.8 years; 16 known satellites.",
        magnitude: 7.8,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },

    // --- stars ---
    polaris: {
        id: "polaris",
        name: "Polaris",
        kind: "star",
        interest: "Stars",
        ra: 37.95,
        dec: 89.264,
        blurb: "Alpha Ursae Minoris; yellow supergiant spectral type F star located 433 light years away.",
        magnitude: 2.0,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sirius: {
        id: "sirius",
        name: "Sirius",
        kind: "star",
        interest: "Stars",
        ra: 101.29,
        dec: -16.716,
        blurb: "Alpha Canis Majoris; binary star system located 8.6 light years away, containing a main-sequence spectral type A star and a white dwarf.",
        magnitude: -1.46,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    vega: {
        id: "vega",
        name: "Vega",
        kind: "star",
        interest: "Stars",
        ra: 279.23,
        dec: 38.784,
        blurb: "Alpha Lyrae; main-sequence spectral type A star located 25 light years away.",
        magnitude: 0.03,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    betelgeuse: {
        id: "betelgeuse",
        name: "Betelgeuse",
        kind: "star",
        interest: "Stars",
        ra: 88.79,
        dec: 7.407,
        blurb: "Alpha Orionis; red supergiant spectral type M star located 640 light years away.",
        magnitude: 0.5,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    rigel: {
        id: "rigel",
        name: "Rigel",
        kind: "star",
        interest: "Stars",
        ra: 78.63,
        dec: -8.2,
        blurb: "Beta Orionis; blue supergiant spectral type B star located 860 light years away.",
        magnitude: 0.13,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    arcturus: {
        id: "arcturus",
        name: "Arcturus",
        kind: "star",
        interest: "Stars",
        ra: 213.92,
        dec: 19.18,
        blurb: "Alpha Boötis; red giant spectral type K star located 37 light years away.",
        magnitude: -0.05,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    capella: {
        id: "capella",
        name: "Capella",
        kind: "star",
        interest: "Stars",
        ra: 79.17,
        dec: 45.998,
        blurb: "Alpha Aurigae; binary star system located 43 light years away, containing two giant spectral type G stars.",
        magnitude: 0.08,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    antares: {
        id: "antares",
        name: "Antares",
        kind: "star",
        interest: "Stars",
        ra: 247.35,
        dec: -26.43,
        blurb: "Alpha Scorpii; red supergiant spectral type M star located 550 light years away.",
        magnitude: 1.06,
        minAltitudeDeg: 12,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    albireo: {
        id: "albireo",
        name: "Albireo",
        kind: "star",
        interest: "Stars",
        ra: 292.68,
        dec: 27.96,
        blurb: "Beta Cygni; binary star system located 430 light years away, containing a giant spectral type K star and a main-sequence spectral type B star.",
        magnitude: 3.1,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mizar: {
        id: "mizar",
        name: "Mizar & Alcor",
        kind: "star",
        interest: "Stars",
        ra: 200.98,
        dec: 54.925,
        blurb: "Zeta Ursae Majoris; multiple star system located 83 light years away, appearing as a naked-eye double with its companion Alcor.",
        magnitude: 2.2,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    altair: {
        id: "altair",
        name: "Altair",
        kind: "star",
        interest: "Stars",
        ra: 297.7,
        dec: 8.87,
        blurb: "Alpha Aquilae; main-sequence spectral type A star located 17 light years away.",
        magnitude: 0.77,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    deneb: {
        id: "deneb",
        name: "Deneb",
        kind: "star",
        interest: "Stars",
        ra: 310.36,
        dec: 45.28,
        blurb: "Alpha Cygni; blue-white supergiant spectral type A star located 2,600 light years away.",
        magnitude: 1.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },

    // --- galaxies ---
    m31: {
        id: "m31",
        name: "M31 — Andromeda Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 10.68,
        dec: 41.269,
        blurb: "M31, NGC 224; Spiral galaxy, the largest member of the Local Group, located 2.5 million light years away.",
        magnitude: 3.4,
        sizeArcmin: 190,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.7,
    },
    m33: {
        id: "m33",
        name: "M33 — Triangulum Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 23.46,
        dec: 30.66,
        blurb: "M33, NGC 598; Spiral galaxy in the Local Group, located 2.7 million light years away.",
        magnitude: 5.7,
        sizeArcmin: 70,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.25,
    },
    m51: {
        id: "m51",
        name: "M51 — Whirlpool Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 202.47,
        dec: 47.195,
        blurb: "M51, NGC 5194; Spiral galaxy interacting with its companion NGC 5195, located 23 million light years away.",
        magnitude: 8.4,
        sizeArcmin: 11,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.35,
    },
    m81: {
        id: "m81",
        name: "M81 & M82 — Bode's Pair",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 148.89,
        dec: 69.065,
        blurb: "M81, NGC 3031; Spiral galaxy in the M81 Group, located 12 million light years away, gravitationally interacting with its neighbor M82.",
        magnitude: 6.9,
        sizeArcmin: 26,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m104: {
        id: "m104",
        name: "M104 — Sombrero Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 189.998,
        dec: -11.62,
        blurb: "M104, NGC 4594; Spiral galaxy in the Virgo Cluster, located 28 million light years away.",
        magnitude: 8.0,
        sizeArcmin: 9,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.4,
    },

    // --- nebulae ---
    m42: {
        id: "m42",
        name: "M42 — Orion Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.82,
        dec: -5.39,
        blurb: "M42, NGC 1976; H II region in the Orion Constellation, located 1,344 light years away.",
        magnitude: 4.0,
        sizeArcmin: 85,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },
    m57: {
        id: "m57",
        name: "M57 — Ring Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 283.4,
        dec: 33.03,
        blurb: "M57, NGC 6720; Planetary nebula in the Lyra Constellation.",
        magnitude: 8.8,
        sizeArcmin: 1.4,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.8,
    },
    m27: {
        id: "m27",
        name: "M27 — Dumbbell Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 299.9,
        dec: 22.72,
        blurb: "M27, NGC 6853; Planetary nebula in the Vulpecula Constellation.",
        magnitude: 7.4,
        sizeArcmin: 8,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.7,
    },
    m8: {
        id: "m8",
        name: "M8 — Lagoon Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 270.9,
        dec: -24.38,
        blurb: "M8, NGC 6523; H II region in the Sagittarius Constellation.",
        magnitude: 6.0,
        sizeArcmin: 90,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m16: {
        id: "m16",
        name: "M16 — Eagle Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 274.7,
        dec: -13.79,
        blurb: "M16, NGC 6611; H II region and star cluster in the Serpens Constellation.",
        magnitude: 6.4,
        sizeArcmin: 7,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.4,
    },
    m17: {
        id: "m17",
        name: "M17 — Omega Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 275.11,
        dec: -16.18,
        blurb: "M17, NGC 6618; H II region in the Sagittarius Constellation.",
        magnitude: 6.0,
        sizeArcmin: 11,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.6,
    },
    ngc7000: {
        id: "ngc7000",
        name: "NGC 7000 — North America Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 314.82,
        dec: 44.52,
        blurb: "NGC 7000; H II region in the Cygnus Constellation.",
        magnitude: 4.0,
        sizeArcmin: 120,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.3,
    },
    veil: {
        id: "veil",
        name: "Veil Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 311.41,
        dec: 30.72,
        blurb: "NGC 6960 & NGC 6992; Supernova remnant in the Cygnus Constellation.",
        magnitude: 7.0,
        sizeArcmin: 180,
        minAltitudeDeg: 40,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.2,
    },

    // --- clusters ---
    m45: {
        id: "m45",
        name: "M45 — Pleiades",
        kind: "cluster",
        interest: "Stars",
        ra: 56.85,
        dec: 24.12,
        blurb: "M45; Open cluster in the Taurus Constellation, located 444 light years away.",
        magnitude: 1.6,
        sizeArcmin: 110,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    m13: {
        id: "m13",
        name: "M13 — Hercules Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 250.42,
        dec: 36.46,
        blurb: "M13, NGC 6205; Globular cluster in the Hercules Constellation, located 22,200 light years away.",
        magnitude: 5.8,
        sizeArcmin: 20,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 25,
        maxMoonIllum: 0.8,
    },
    m44: {
        id: "m44",
        name: "M44 — Beehive Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 130.1,
        dec: 19.67,
        blurb: "M44, NGC 2632; Open cluster in the Cancer Constellation, located 577 light years away.",
        magnitude: 3.7,
        sizeArcmin: 95,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.9,
    },
    m7: {
        id: "m7",
        name: "M7 — Ptolemy Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 268.46,
        dec: -34.79,
        blurb: "M7, NGC 6475; Open cluster in the Scorpius Constellation, located 980 light years away.",
        magnitude: 3.3,
        sizeArcmin: 80,
        minAltitudeDeg: 10,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },
    "double-cluster": {
        id: "double-cluster",
        name: "Double Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 34.75,
        dec: 57.13,
        blurb: "NGC 869 & NGC 884; Pair of open clusters in the Perseus Constellation, located 7,600 light years away.",
        magnitude: 4.3,
        sizeArcmin: 60,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.9,
    },

    // --- stars (catalog fill) ---
    canopus: {
        id: "canopus",
        name: "Canopus",
        kind: "star",
        interest: "Stars",
        ra: 95.988,
        dec: -52.696,
        blurb: "Alpha Carinae; blue loop giant spectral type A star located 310 light years away.",
        magnitude: -0.62,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    "alpha-centauri": {
        id: "alpha-centauri",
        name: "Alpha Centauri",
        kind: "star",
        interest: "Stars",
        ra: 219.902,
        dec: -60.834,
        blurb: "Alpha Centauri; triple star system located 4.3 light years away, containing a main-sequence spectral type G star, a main-sequence spectral type K star, and a main-sequence spectral type M star.",
        magnitude: -0.01,
        minAltitudeDeg: 15,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    procyon: {
        id: "procyon",
        name: "Procyon",
        kind: "star",
        interest: "Stars",
        ra: 114.825,
        dec: 5.225,
        blurb: "Alpha Canis Minoris; binary star system located 11.5 light years away, containing a main-sequence spectral type F star and a white dwarf.",
        magnitude: 0.4,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    achernar: {
        id: "achernar",
        name: "Achernar",
        kind: "star",
        interest: "Stars",
        ra: 24.429,
        dec: -57.237,
        blurb: "Alpha Eridani; main-sequence spectral type B star located 139 light years away.",
        magnitude: 0.45,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    hadar: {
        id: "hadar",
        name: "Hadar",
        kind: "star",
        interest: "Stars",
        ra: 210.956,
        dec: -60.373,
        blurb: "Beta Centauri; triple star system located 390 light years away, containing two blue giant spectral type B stars and a third fainter companion.",
        magnitude: 0.61,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    acrux: {
        id: "acrux",
        name: "Acrux",
        kind: "star",
        interest: "Stars",
        ra: 186.65,
        dec: -63.099,
        blurb: "Alpha Crucis; multiple star system located 320 light years away, containing two main-sequence spectral type B stars and two more distant companions.",
        magnitude: 1.33,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    aldebaran: {
        id: "aldebaran",
        name: "Aldebaran",
        kind: "star",
        interest: "Stars",
        ra: 68.98,
        dec: 16.509,
        blurb: "Alpha Tauri; red giant spectral type K star located 65 light years away.",
        magnitude: 0.87,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    spica: {
        id: "spica",
        name: "Spica",
        kind: "star",
        interest: "Stars",
        ra: 201.298,
        dec: -11.161,
        blurb: "Alpha Virginis; binary star system located 250 light years away, containing two main-sequence spectral type B stars.",
        magnitude: 0.98,
        minAltitudeDeg: 18,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 50,
        maxMoonIllum: 1,
    },
    pollux: {
        id: "pollux",
        name: "Pollux",
        kind: "star",
        interest: "Stars",
        ra: 116.329,
        dec: 28.026,
        blurb: "Beta Geminorum; orange giant spectral type K star located 34 light years away.",
        magnitude: 1.16,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    fomalhaut: {
        id: "fomalhaut",
        name: "Fomalhaut",
        kind: "star",
        interest: "Stars",
        ra: 344.413,
        dec: -29.622,
        blurb: "Alpha Piscis Austrini; main-sequence spectral type A star located 25 light years away.",
        magnitude: 1.17,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mimosa: {
        id: "mimosa",
        name: "Mimosa",
        kind: "star",
        interest: "Stars",
        ra: 191.93,
        dec: -59.689,
        blurb: "Beta Crucis; binary star system located 280 light years away, containing a blue giant spectral type B star and a smaller companion.",
        magnitude: 1.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    regulus: {
        id: "regulus",
        name: "Regulus",
        kind: "star",
        interest: "Stars",
        ra: 152.093,
        dec: 11.967,
        blurb: "Alpha Leonis; multiple star system located 79 light years away, containing a main-sequence spectral type B star and three smaller companions.",
        magnitude: 1.36,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    adhara: {
        id: "adhara",
        name: "Adhara",
        kind: "star",
        interest: "Stars",
        ra: 104.656,
        dec: -28.972,
        blurb: "Epsilon Canis Majoris; binary star system located 430 light years away, containing a blue giant spectral type B star and a smaller companion.",
        magnitude: 1.5,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    castor: {
        id: "castor",
        name: "Castor",
        kind: "star",
        interest: "Stars",
        ra: 113.649,
        dec: 31.888,
        blurb: "Alpha Geminorum; multiple star system located 51 light years away, containing six stars in three binary pairs.",
        magnitude: 1.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    shaula: {
        id: "shaula",
        name: "Shaula",
        kind: "star",
        interest: "Stars",
        ra: 263.402,
        dec: -37.104,
        blurb: "Lambda Scorpii; multiple star system located 570 light years away, containing a blue subgiant spectral type B star and two companions.",
        magnitude: 1.62,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    gacrux: {
        id: "gacrux",
        name: "Gacrux",
        kind: "star",
        interest: "Stars",
        ra: 187.791,
        dec: -57.113,
        blurb: "Gamma Crucis; red giant spectral type M star located 88 light years away.",
        magnitude: 1.59,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    bellatrix: {
        id: "bellatrix",
        name: "Bellatrix",
        kind: "star",
        interest: "Stars",
        ra: 81.283,
        dec: 6.35,
        blurb: "Gamma Orionis; main-sequence spectral type B star located 250 light years away.",
        magnitude: 1.64,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    elnath: {
        id: "elnath",
        name: "Elnath",
        kind: "star",
        interest: "Stars",
        ra: 81.573,
        dec: 28.607,
        blurb: "Beta Tauri; main-sequence spectral type B star located 130 light years away.",
        magnitude: 1.65,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    miaplacidus: {
        id: "miaplacidus",
        name: "Miaplacidus",
        kind: "star",
        interest: "Stars",
        ra: 138.3,
        dec: -69.717,
        blurb: "Beta Carinae; main-sequence spectral type A star located 113 light years away.",
        magnitude: 1.67,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnilam: {
        id: "alnilam",
        name: "Alnilam",
        kind: "star",
        interest: "Stars",
        ra: 84.053,
        dec: -1.202,
        blurb: "Epsilon Orionis; blue supergiant spectral type B star located 2,000 light years away.",
        magnitude: 1.69,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnair: {
        id: "alnair",
        name: "Alnair",
        kind: "star",
        interest: "Stars",
        ra: 332.058,
        dec: -46.961,
        blurb: "Alpha Gruis; main-sequence spectral type B star located 101 light years away.",
        magnitude: 1.73,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alnitak: {
        id: "alnitak",
        name: "Alnitak",
        kind: "star",
        interest: "Stars",
        ra: 85.19,
        dec: -1.943,
        blurb: "Zeta Orionis; multiple star system located 800 light years away, containing a blue supergiant spectral type O star and two companions.",
        magnitude: 1.74,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alioth: {
        id: "alioth",
        name: "Alioth",
        kind: "star",
        interest: "Stars",
        ra: 193.507,
        dec: 55.96,
        blurb: "Epsilon Ursae Majoris; main-sequence spectral type A star located 83 light years away.",
        magnitude: 1.76,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    dubhe: {
        id: "dubhe",
        name: "Dubhe",
        kind: "star",
        interest: "Stars",
        ra: 165.932,
        dec: 61.751,
        blurb: "Alpha Ursae Majoris; binary star system located 123 light years away, containing a giant spectral type K star and a main-sequence spectral type F star.",
        magnitude: 1.81,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mirfak: {
        id: "mirfak",
        name: "Mirfak",
        kind: "star",
        interest: "Stars",
        ra: 51.081,
        dec: 49.861,
        blurb: "Alpha Persei; supergiant spectral type F star located 590 light years away.",
        magnitude: 1.79,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    wezen: {
        id: "wezen",
        name: "Wezen",
        kind: "star",
        interest: "Stars",
        ra: 107.098,
        dec: -26.393,
        blurb: "Delta Canis Majoris; yellow-white supergiant spectral type F star located 1,600 light years away.",
        magnitude: 1.83,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    "gamma-velorum": {
        id: "gamma-velorum",
        name: "Gamma Velorum",
        kind: "star",
        interest: "Stars",
        ra: 122.383,
        dec: -47.337,
        blurb: "Gamma Velorum; multiple star system located 840 light years away, containing a Wolf-Rayet star and a blue giant spectral type O companion.",
        magnitude: 1.75,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    sargas: {
        id: "sargas",
        name: "Sargas",
        kind: "star",
        interest: "Stars",
        ra: 264.33,
        dec: -42.998,
        blurb: "Theta Scorpii; yellow-white giant spectral type F star located 270 light years away.",
        magnitude: 1.86,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    "kaus-australis": {
        id: "kaus-australis",
        name: "Kaus Australis",
        kind: "star",
        interest: "Stars",
        ra: 276.043,
        dec: -34.385,
        blurb: "Epsilon Sagittarii; giant spectral type B star located 143 light years away.",
        magnitude: 1.79,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    avior: {
        id: "avior",
        name: "Avior",
        kind: "star",
        interest: "Stars",
        ra: 125.628,
        dec: -59.509,
        blurb: "Epsilon Carinae; binary star system located 630 light years away, containing an orange giant spectral type K star and a blue-white companion.",
        magnitude: 1.86,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alkaid: {
        id: "alkaid",
        name: "Alkaid",
        kind: "star",
        interest: "Stars",
        ra: 206.885,
        dec: 49.313,
        blurb: "Eta Ursae Majoris; main-sequence spectral type B star located 104 light years away.",
        magnitude: 1.85,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    menkalinan: {
        id: "menkalinan",
        name: "Menkalinan",
        kind: "star",
        interest: "Stars",
        ra: 89.882,
        dec: 44.947,
        blurb: "Beta Aurigae; binary star system located 82 light years away, containing two main-sequence spectral type A stars.",
        magnitude: 1.9,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    atria: {
        id: "atria",
        name: "Atria",
        kind: "star",
        interest: "Stars",
        ra: 252.166,
        dec: -69.028,
        blurb: "Alpha Trianguli Australis; orange giant spectral type K star located 415 light years away.",
        magnitude: 1.91,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alhena: {
        id: "alhena",
        name: "Alhena",
        kind: "star",
        interest: "Stars",
        ra: 99.428,
        dec: 16.399,
        blurb: "Gamma Geminorum; main-sequence spectral type A star located 109 light years away.",
        magnitude: 1.93,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    peacock: {
        id: "peacock",
        name: "Peacock",
        kind: "star",
        interest: "Stars",
        ra: 306.412,
        dec: -56.735,
        blurb: "Alpha Pavonis; binary star system located 183 light years away, containing a blue-white spectral type B star and a smaller companion.",
        magnitude: 1.94,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alsephina: {
        id: "alsephina",
        name: "Alsephina",
        kind: "star",
        interest: "Stars",
        ra: 131.176,
        dec: -54.709,
        blurb: "Delta Velorum; multiple star system located 80 light years away, containing an eclipsing binary of two main-sequence spectral type A stars and two more distant companions.",
        magnitude: 1.99,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    mirzam: {
        id: "mirzam",
        name: "Mirzam",
        kind: "star",
        interest: "Stars",
        ra: 95.675,
        dec: -17.956,
        blurb: "Beta Canis Majoris; blue giant spectral type B star located 500 light years away.",
        magnitude: 1.98,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    alphard: {
        id: "alphard",
        name: "Alphard",
        kind: "star",
        interest: "Stars",
        ra: 141.897,
        dec: -8.659,
        blurb: "Alpha Hydrae; orange giant spectral type K star located 177 light years away.",
        magnitude: 1.99,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -6,
        maxCloudPct: 45,
        maxMoonIllum: 1,
    },
    hamal: {
        id: "hamal",
        name: "Hamal",
        kind: "star",
        interest: "Stars",
        ra: 31.793,
        dec: 23.462,
        blurb: "Alpha Arietis; orange giant spectral type K star located 66 light years away.",
        magnitude: 2.01,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    diphda: {
        id: "diphda",
        name: "Diphda",
        kind: "star",
        interest: "Stars",
        ra: 10.897,
        dec: -17.987,
        blurb: "Beta Ceti; orange giant spectral type K star located 96 light years away.",
        magnitude: 2.04,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    nunki: {
        id: "nunki",
        name: "Nunki",
        kind: "star",
        interest: "Stars",
        ra: 283.816,
        dec: -26.297,
        blurb: "Sigma Sagittarii; main-sequence spectral type B star located 228 light years away.",
        magnitude: 2.05,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    menkent: {
        id: "menkent",
        name: "Menkent",
        kind: "star",
        interest: "Stars",
        ra: 211.671,
        dec: -36.37,
        blurb: "Theta Centauri; orange giant spectral type K star located 61 light years away.",
        magnitude: 2.06,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alpheratz: {
        id: "alpheratz",
        name: "Alpheratz",
        kind: "star",
        interest: "Stars",
        ra: 2.097,
        dec: 29.09,
        blurb: "Alpha Andromedae; binary star system located 97 light years away, containing a main-sequence spectral type B star and a chemically peculiar companion.",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mirach: {
        id: "mirach",
        name: "Mirach",
        kind: "star",
        interest: "Stars",
        ra: 17.433,
        dec: 35.621,
        blurb: "Beta Andromedae; red giant spectral type M star located 197 light years away.",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    rasalhague: {
        id: "rasalhague",
        name: "Rasalhague",
        kind: "star",
        interest: "Stars",
        ra: 263.734,
        dec: 12.56,
        blurb: "Alpha Ophiuchi; binary star system located 49 light years away, containing a main-sequence spectral type A star and a smaller companion.",
        magnitude: 2.08,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    algieba: {
        id: "algieba",
        name: "Algieba",
        kind: "star",
        interest: "Stars",
        ra: 154.993,
        dec: 19.841,
        blurb: "Gamma Leonis; binary star system located 130 light years away, containing two orange giant spectral type K stars.",
        magnitude: 2.61,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    kochab: {
        id: "kochab",
        name: "Kochab",
        kind: "star",
        interest: "Stars",
        ra: 222.676,
        dec: 74.156,
        blurb: "Beta Ursae Minoris; orange giant spectral type K star located 126 light years away.",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    saiph: {
        id: "saiph",
        name: "Saiph",
        kind: "star",
        interest: "Stars",
        ra: 86.939,
        dec: -9.67,
        blurb: "Kappa Orionis; blue supergiant spectral type B star located 720 light years away.",
        magnitude: 2.07,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    denebola: {
        id: "denebola",
        name: "Denebola",
        kind: "star",
        interest: "Stars",
        ra: 177.265,
        dec: 14.572,
        blurb: "Beta Leonis; main-sequence spectral type A star located 36 light years away.",
        magnitude: 2.14,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    algol: {
        id: "algol",
        name: "Algol",
        kind: "star",
        interest: "Stars",
        ra: 47.042,
        dec: 40.956,
        blurb: "Beta Persei; eclipsing binary star system located 90 light years away, containing a main-sequence spectral type B star and a subgiant spectral type K star.",
        magnitude: 2.09,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    tiaki: {
        id: "tiaki",
        name: "Tiaki",
        kind: "star",
        interest: "Stars",
        ra: 340.667,
        dec: -46.885,
        blurb: "Beta Gruis; red giant spectral type M star located 170 light years away.",
        magnitude: 2.12,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    muhlifain: {
        id: "muhlifain",
        name: "Muhlifain",
        kind: "star",
        interest: "Stars",
        ra: 190.379,
        dec: -48.96,
        blurb: "Gamma Centauri; binary star system located 130 light years away, containing two main-sequence spectral type A stars.",
        magnitude: 2.2,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aspidiske: {
        id: "aspidiske",
        name: "Aspidiske",
        kind: "star",
        interest: "Stars",
        ra: 139.273,
        dec: -59.275,
        blurb: "Iota Carinae; white supergiant spectral type A star located 690 light years away.",
        magnitude: 2.21,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    suhail: {
        id: "suhail",
        name: "Suhail",
        kind: "star",
        interest: "Stars",
        ra: 136.999,
        dec: -43.433,
        blurb: "Lambda Velorum; orange supergiant spectral type K star located 570 light years away.",
        magnitude: 2.23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alphecca: {
        id: "alphecca",
        name: "Alphecca",
        kind: "star",
        interest: "Stars",
        ra: 233.672,
        dec: 26.715,
        blurb: "Alpha Coronae Borealis; binary star system located 75 light years away, containing a main-sequence spectral type A star and a main-sequence spectral type G star.",
        magnitude: 2.22,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    mintaka: {
        id: "mintaka",
        name: "Mintaka",
        kind: "star",
        interest: "Stars",
        ra: 83.002,
        dec: -0.299,
        blurb: "Delta Orionis; multiple star system located 1,200 light years away, containing an eclipsing binary of blue giant spectral type O and B stars.",
        magnitude: 2.25,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sadr: {
        id: "sadr",
        name: "Sadr",
        kind: "star",
        interest: "Stars",
        ra: 305.557,
        dec: 40.257,
        blurb: "Gamma Cygni; supergiant spectral type F star located 1,800 light years away.",
        magnitude: 2.23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    eltanin: {
        id: "eltanin",
        name: "Eltanin",
        kind: "star",
        interest: "Stars",
        ra: 269.152,
        dec: 51.489,
        blurb: "Gamma Draconis; orange giant spectral type K star located 154 light years away.",
        magnitude: 2.24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    schedar: {
        id: "schedar",
        name: "Schedar",
        kind: "star",
        interest: "Stars",
        ra: 10.127,
        dec: 56.537,
        blurb: "Alpha Cassiopeiae; orange giant spectral type K star located 228 light years away.",
        magnitude: 2.24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    naos: {
        id: "naos",
        name: "Naos",
        kind: "star",
        interest: "Stars",
        ra: 120.896,
        dec: -40.003,
        blurb: "Zeta Puppis; blue supergiant spectral type O star located 1,080 light years away.",
        magnitude: 2.21,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    almach: {
        id: "almach",
        name: "Almach",
        kind: "star",
        interest: "Stars",
        ra: 30.975,
        dec: 42.33,
        blurb: "Gamma Andromedae; multiple star system located 350 light years away, containing an orange giant spectral type K star and a blue-white binary companion.",
        magnitude: 2.1,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    caph: {
        id: "caph",
        name: "Caph",
        kind: "star",
        interest: "Stars",
        ra: 2.295,
        dec: 59.15,
        blurb: "Beta Cassiopeiae; subgiant spectral type F star located 55 light years away.",
        magnitude: 2.28,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    izar: {
        id: "izar",
        name: "Izar",
        kind: "star",
        interest: "Stars",
        ra: 221.247,
        dec: 27.074,
        blurb: "Epsilon Boötis; binary star system located 210 light years away, containing an orange giant spectral type K star and a main-sequence spectral type A star.",
        magnitude: 2.35,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    uridim: {
        id: "uridim",
        name: "Uridim",
        kind: "star",
        interest: "Stars",
        ra: 230.671,
        dec: -44.684,
        blurb: "Epsilon Centauri; main-sequence spectral type B star located 430 light years away.",
        magnitude: 3.37,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 35,
        maxMoonIllum: 0.9,
    },
    "epsilon-centauri": {
        id: "epsilon-centauri",
        name: "Epsilon Centauri",
        kind: "star",
        interest: "Stars",
        ra: 204.972,
        dec: -53.466,
        blurb: "Epsilon Centauri; main-sequence spectral type B star located 430 light years away.",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    dschubba: {
        id: "dschubba",
        name: "Dschubba",
        kind: "star",
        interest: "Stars",
        ra: 240.083,
        dec: -22.622,
        blurb: "Delta Scorpii; binary star system located 400 light years away, containing a blue subgiant spectral type B star and a smaller companion.",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    larawag: {
        id: "larawag",
        name: "Larawag",
        kind: "star",
        interest: "Stars",
        ra: 252.541,
        dec: -34.293,
        blurb: "Epsilon Scorpii; orange giant spectral type K star located 65 light years away.",
        magnitude: 2.29,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "eta-centauri": {
        id: "eta-centauri",
        name: "Eta Centauri",
        kind: "star",
        interest: "Stars",
        ra: 218.877,
        dec: -42.158,
        blurb: "Eta Centauri; main-sequence spectral type B star located 308 light years away.",
        magnitude: 2.33,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    merak: {
        id: "merak",
        name: "Merak",
        kind: "star",
        interest: "Stars",
        ra: 165.46,
        dec: 56.382,
        blurb: "Beta Ursae Majoris; main-sequence spectral type A star located 79 light years away.",
        magnitude: 2.34,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    ankaa: {
        id: "ankaa",
        name: "Ankaa",
        kind: "star",
        interest: "Stars",
        ra: 6.571,
        dec: -42.306,
        blurb: "Alpha Phoenicis; orange giant spectral type K star located 82 light years away.",
        magnitude: 2.4,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    girtab: {
        id: "girtab",
        name: "Girtab",
        kind: "star",
        interest: "Stars",
        ra: 265.622,
        dec: -39.03,
        blurb: "Kappa Scorpii; blue giant spectral type B star located 480 light years away.",
        magnitude: 2.41,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    enif: {
        id: "enif",
        name: "Enif",
        kind: "star",
        interest: "Stars",
        ra: 326.046,
        dec: 9.875,
        blurb: "Epsilon Pegasi; orange supergiant spectral type K star located 690 light years away.",
        magnitude: 2.38,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    scheat: {
        id: "scheat",
        name: "Scheat",
        kind: "star",
        interest: "Stars",
        ra: 345.944,
        dec: 28.083,
        blurb: "Beta Pegasi; red giant spectral type M star located 196 light years away.",
        magnitude: 2.44,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    sabik: {
        id: "sabik",
        name: "Sabik",
        kind: "star",
        interest: "Stars",
        ra: 257.595,
        dec: -15.725,
        blurb: "Eta Ophiuchi; binary star system located 88 light years away, containing two main-sequence spectral type A stars.",
        magnitude: 2.43,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    phecda: {
        id: "phecda",
        name: "Phecda",
        kind: "star",
        interest: "Stars",
        ra: 178.458,
        dec: 53.695,
        blurb: "Gamma Ursae Majoris; main-sequence spectral type A star located 84 light years away.",
        magnitude: 2.41,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aludra: {
        id: "aludra",
        name: "Aludra",
        kind: "star",
        interest: "Stars",
        ra: 111.024,
        dec: -29.303,
        blurb: "Eta Canis Majoris; blue supergiant spectral type B star located 2,000 light years away.",
        magnitude: 2.45,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    alderamin: {
        id: "alderamin",
        name: "Alderamin",
        kind: "star",
        interest: "Stars",
        ra: 319.645,
        dec: 62.586,
        blurb: "Alpha Cephei; main-sequence spectral type A star located 49 light years away.",
        magnitude: 2.45,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    markeb: {
        id: "markeb",
        name: "Markeb",
        kind: "star",
        interest: "Stars",
        ra: 140.528,
        dec: -55.011,
        blurb: "Kappa Velorum; main-sequence spectral type B star located 570 light years away.",
        magnitude: 2.47,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    tiansi: {
        id: "tiansi",
        name: "Tiansi (Gamma Cassiopeiae)",
        kind: "star",
        interest: "Stars",
        ra: 14.177,
        dec: 60.717,
        blurb: "Gamma Cassiopeiae; eruptive variable spectral type B star located 550 light years away.",
        magnitude: 2.47,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    markab: {
        id: "markab",
        name: "Markab",
        kind: "star",
        interest: "Stars",
        ra: 346.19,
        dec: 15.205,
        blurb: "Alpha Pegasi; main-sequence spectral type B star located 133 light years away.",
        magnitude: 2.49,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    aljanah: {
        id: "aljanah",
        name: "Aljanah",
        kind: "star",
        interest: "Stars",
        ra: 311.553,
        dec: 33.97,
        blurb: "Epsilon Cygni; orange giant spectral type K star located 72 light years away.",
        magnitude: 2.48,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    acrab: {
        id: "acrab",
        name: "Acrab",
        kind: "star",
        interest: "Stars",
        ra: 241.359,
        dec: -19.805,
        blurb: "Beta Scorpii; multiple star system located 400 light years away, containing two blue-white spectral type B stars.",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    muliphein: {
        id: "muliphein",
        name: "Muliphein",
        kind: "star",
        interest: "Stars",
        ra: 105.94,
        dec: -15.633,
        blurb: "Gamma Canis Majoris; blue-white giant spectral type B star located 402 light years away.",
        magnitude: 4.11,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.8,
    },
    tureis: {
        id: "tureis",
        name: "Tureis",
        kind: "star",
        interest: "Stars",
        ra: 121.886,
        dec: -24.304,
        blurb: "Rho Puppis; yellow-white giant spectral type F star located 63 light years away.",
        magnitude: 2.83,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "zeta-ophiuchi": {
        id: "zeta-ophiuchi",
        name: "Zeta Ophiuchi",
        kind: "star",
        interest: "Stars",
        ra: 249.29,
        dec: -10.567,
        blurb: "Zeta Ophiuchi; main-sequence spectral type O star located 366 light years away.",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    menkar: {
        id: "menkar",
        name: "Menkar",
        kind: "star",
        interest: "Stars",
        ra: 45.57,
        dec: 4.09,
        blurb: "Alpha Ceti; red giant spectral type M star located 220 light years away.",
        magnitude: 2.54,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    zosma: {
        id: "zosma",
        name: "Zosma",
        kind: "star",
        interest: "Stars",
        ra: 168.527,
        dec: 20.524,
        blurb: "Delta Leonis; main-sequence spectral type A star located 58 light years away.",
        magnitude: 2.56,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    "delta-centauri": {
        id: "delta-centauri",
        name: "Delta Centauri",
        kind: "star",
        interest: "Stars",
        ra: 182.09,
        dec: -50.723,
        blurb: "Delta Centauri; blue-white giant spectral type B star located 395 light years away.",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    arneb: {
        id: "arneb",
        name: "Arneb",
        kind: "star",
        interest: "Stars",
        ra: 83.183,
        dec: -17.822,
        blurb: "Alpha Leporis; yellow supergiant spectral type F star located 1,300 light years away.",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },
    gienah: {
        id: "gienah",
        name: "Gienah",
        kind: "star",
        interest: "Stars",
        ra: 183.952,
        dec: -17.542,
        blurb: "Gamma Corvi; blue giant spectral type B star located 154 light years away.",
        magnitude: 2.58,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -8,
        maxCloudPct: 40,
        maxMoonIllum: 1,
    },

    // --- galaxies (catalog fill) ---
    m32: {
        id: "m32",
        name: "M32",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 10.674,
        dec: 40.865,
        blurb: "M32, NGC 221; Dwarf satellite galaxy of Andromeda, located 2.5 million light years away.",
        magnitude: 8.1,
        sizeArcmin: 7.6,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.65,
    },
    m49: {
        id: "m49",
        name: "M49",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 187.445,
        dec: 8.001,
        blurb: "M49, NGC 4472; Giant elliptical galaxy in the Virgo Cluster, located 56 million light years away.",
        magnitude: 8.4,
        sizeArcmin: 10.2,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m58: {
        id: "m58",
        name: "M58",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 189.431,
        dec: 11.818,
        blurb: "M58, NGC 4579; Intermediate barred spiral galaxy in the Virgo Cluster, located 68 million light years away.",
        magnitude: 9.7,
        sizeArcmin: 5.9,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m59: {
        id: "m59",
        name: "M59",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 190.51,
        dec: 11.647,
        blurb: "M59, NGC 4621; Elliptical galaxy in the Virgo Cluster, located 50 million light years away.",
        magnitude: 9.6,
        sizeArcmin: 5.4,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m60: {
        id: "m60",
        name: "M60",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 190.915,
        dec: 11.553,
        blurb: "M60, NGC 4649; Elliptical galaxy in the Virgo Cluster, located 57 million light years away.",
        magnitude: 8.8,
        sizeArcmin: 7.4,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m61: {
        id: "m61",
        name: "M61",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 185.479,
        dec: 4.474,
        blurb: "M61, NGC 4303, Swelling Spiral Galaxy; Intermediate barred spiral galaxy in the Virgo Cluster, located 53 million light years away.",
        magnitude: 9.7,
        sizeArcmin: 6.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m63: {
        id: "m63",
        name: "M63 — Sunflower Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 198.955,
        dec: 42.029,
        blurb: "M63, NGC 5055, Sunflower Galaxy; Spiral galaxy in the M51 Group, located 29 million light years away.",
        magnitude: 8.6,
        sizeArcmin: 12.6,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m64: {
        id: "m64",
        name: "M64 — Black Eye Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 194.182,
        dec: 21.683,
        blurb: "M64, NGC 4826; Spiral galaxy in the Coma Berenices Constellation, located 17 million light years away.",
        magnitude: 8.5,
        sizeArcmin: 10.7,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m74: {
        id: "m74",
        name: "M74 — Phantom Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 24.174,
        dec: 15.784,
        blurb: "M74, NGC 628; Spiral galaxy in the Pisces Constellation, located 32 million light years away.",
        magnitude: 9.4,
        sizeArcmin: 10.5,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },
    m77: {
        id: "m77",
        name: "M77 — Squid Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 40.67,
        dec: -0.013,
        blurb: "M77, NGC 1068; Barred spiral galaxy in the Cetus Constellation, located 47 million light years away.",
        magnitude: 8.9,
        sizeArcmin: 7.1,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m83: {
        id: "m83",
        name: "M83 — Southern Pinwheel Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 204.254,
        dec: -29.866,
        blurb: "M83, NGC 5236; Barred spiral galaxy in the Hydra Constellation, located 15 million light years away.",
        magnitude: 7.6,
        sizeArcmin: 12.9,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.4,
    },
    m87: {
        id: "m87",
        name: "M87 — Virgo A",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 187.706,
        dec: 12.391,
        blurb: "M87, NGC 4486; Giant elliptical galaxy in the Virgo Cluster, located 53 million light years away, host to a supermassive black hole imaged by the Event Horizon Telescope.",
        magnitude: 8.6,
        sizeArcmin: 7.2,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.6,
    },
    m101: {
        id: "m101",
        name: "M101 — Pinwheel Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 210.803,
        dec: 54.349,
        blurb: "M101, NGC 5457; Spiral galaxy in the Ursa Major Constellation, located 21 million light years away.",
        magnitude: 7.9,
        sizeArcmin: 28.8,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.4,
    },
    m102: {
        id: "m102",
        name: "M102 — Spindle Galaxy",
        kind: "galaxy",
        interest: "Galaxies",
        ra: 226.623,
        dec: 55.763,
        blurb: "M102, NGC 5866; Lenticular galaxy in the Draco Constellation, located 50 million light years away.",
        magnitude: 9.9,
        sizeArcmin: 4.7,
        minAltitudeDeg: 28,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 10,
        maxMoonIllum: 0.6,
    },

    // --- nebulae (catalog fill) ---
    m1: {
        id: "m1",
        name: "M1 — Crab Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.633,
        dec: 22.015,
        blurb: "M1, NGC 1952, Crab Nebula; Supernova remnant in the Taurus Constellation messier 20.",
        magnitude: 8.4,
        sizeArcmin: 7,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    m20: {
        id: "m20",
        name: "M20 — Trifid Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 270.596,
        dec: -23.03,
        blurb: "M20, NGC 6514, Trifid Nebula; H II region in the Sagittarius Constellation messier 43.",
        magnitude: 6.3,
        sizeArcmin: 28,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    m43: {
        id: "m43",
        name: "M43 — De Mairan's Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 83.9,
        dec: -5.267,
        blurb: "M43, NGC 1982, De Mairan’s Nebula; H II region and molecular cloud in the Orion Constellation.",
        magnitude: 9.0,
        sizeArcmin: 20,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.55,
    },
    m97: {
        id: "m97",
        name: "M97 — Owl Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 168.699,
        dec: 55.019,
        blurb: "M97, NGC 3587; Planetary nebula in the Ursa Major Constellation.",
        magnitude: 9.9,
        sizeArcmin: 3.4,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.65,
    },
    ngc6543: {
        id: "ngc6543",
        name: "NGC 6543 — Cat's Eye Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 269.639,
        dec: 66.633,
        blurb: "NGC 6543; Planetary nebula in the Draco Constellation.",
        magnitude: 8.1,
        sizeArcmin: 0.3,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.75,
    },
    ngc7635: {
        id: "ngc7635",
        name: "NGC 7635 — Bubble Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 350.201,
        dec: 61.202,
        blurb: "NGC 7635; H II region in the Cassiopeia Constellation.",
        magnitude: 10.0,
        sizeArcmin: 15,
        minAltitudeDeg: 35,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.55,
    },
    ngc7293: {
        id: "ngc7293",
        name: "NGC 7293 — Helix Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 337.411,
        dec: -20.837,
        blurb: "NGC 7293; Planetary nebula in the Aquarius Constellation, one of the closest planetary nebulae to Earth.",
        magnitude: 7.6,
        sizeArcmin: 25,
        minAltitudeDeg: 30,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 20,
        maxMoonIllum: 0.5,
    },
    ngc3132: {
        id: "ngc3132",
        name: "NGC 3132 — Southern Ring Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 151.757,
        dec: -40.436,
        blurb: "NGC 3132; Planetary nebula in the Vela Constellation.",
        magnitude: 9.9,
        sizeArcmin: 1,
        minAltitudeDeg: 26,
        maxSunAltitudeDeg: -18,
        maxCloudPct: 15,
        maxMoonIllum: 0.7,
    },
    ngc3372: {
        id: "ngc3372",
        name: "NGC 3372 — Carina Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 161.285,
        dec: -59.868,
        blurb: "NGC 3372; H II region in the Carina Constellation, home to the massive star Eta Carinae.",
        magnitude: 1.0,
        sizeArcmin: 120,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    ngc2174: {
        id: "ngc2174",
        name: "NGC 2174 — Monkey Head Nebula",
        kind: "nebula",
        interest: "Nebulae",
        ra: 92.425,
        dec: 20.5,
        blurb: "NGC 2174; H II region in the Orion Constellation.",
        magnitude: 6.8,
        sizeArcmin: 40,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 25,
        maxMoonIllum: 0.6,
    },
    ngc2313: {
        id: "ngc2313",
        name: "NGC 2313",
        kind: "nebula",
        interest: "Nebulae",
        ra: 104.829,
        dec: -7.982,
        blurb: "NGC 2313; Reflection and emission nebula in the Monoceros Constellation.",
        magnitude: 14.2,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },

    // --- clusters (catalog fill) ---
    m4: {
        id: "m4",
        name: "M4 — Spider Globular Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 245.897,
        dec: -26.526,
        blurb: "M4, NGC 6121; Globular cluster in the Scorpius Constellation, located 7,200 light years away.",
        magnitude: 5.6,
        sizeArcmin: 26,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m5: {
        id: "m5",
        name: "M5 — Rose Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 229.638,
        dec: 2.081,
        blurb: "M5, NGC 5904; Globular cluster in the Serpens Constellation, located 24,500 light years away.",
        magnitude: 5.6,
        sizeArcmin: 23,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m6: {
        id: "m6",
        name: "M6 — Butterfly Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 265.025,
        dec: -32.217,
        blurb: "M6, NGC 6405; Open cluster in the Scorpius Constellation, located 1,600 light years away.",
        magnitude: 4.2,
        sizeArcmin: 25,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m11: {
        id: "m11",
        name: "M11 — Wild Duck Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 282.775,
        dec: -6.267,
        blurb: "M11, NGC 6705; Open cluster in the Scutum Constellation, located 6,200 light years away.",
        magnitude: 5.8,
        sizeArcmin: 22.8,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m15: {
        id: "m15",
        name: "M15 — Great Pegasus Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 322.493,
        dec: 12.167,
        blurb: "M15, NGC 7078; Globular cluster in the Pegasus Constellation, located 33,600 light years away.",
        magnitude: 6.2,
        sizeArcmin: 18,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m18: {
        id: "m18",
        name: "M18 — Black Swan Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 274.975,
        dec: -17.133,
        blurb: "M18, NGC 6613; Open cluster in the Sagittarius Constellation, located 4,900 light years away.",
        magnitude: 7.5,
        sizeArcmin: 9.8,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m30: {
        id: "m30",
        name: "M30 — Jellyfish Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 325.092,
        dec: -23.18,
        blurb: "M30, NGC 7099; Globular cluster in the Capricornus Constellation, located 27,100 light years away.",
        magnitude: 7.2,
        sizeArcmin: 12,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m35: {
        id: "m35",
        name: "M35 — Shoe-Buckle Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 92.275,
        dec: 24.35,
        blurb: "M35, NGC 2168; Open cluster in the Gemini Constellation, located 2,800 light years away.",
        magnitude: 5.3,
        sizeArcmin: 28,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m36: {
        id: "m36",
        name: "M36 — Pinwheel Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 84.05,
        dec: 34.134,
        blurb: "M36, NGC 1960; Open cluster in the Auriga Constellation, located 4,100 light years away.",
        magnitude: 6.3,
        sizeArcmin: 12,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m37: {
        id: "m37",
        name: "M37 — Salt and Pepper Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 88.075,
        dec: 32.551,
        blurb: "M37, NGC 2099; Open cluster in the Auriga Constellation, located 4,500 light years away.",
        magnitude: 6.2,
        sizeArcmin: 24,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
    m38: {
        id: "m38",
        name: "M38 — Starfish Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 82.175,
        dec: 35.855,
        blurb: "M38, NGC 1912; Open cluster in the Auriga Constellation, located 4,200 light years away.",
        magnitude: 7.4,
        sizeArcmin: 21,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m39: {
        id: "m39",
        name: "M39 — Pyramid Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 322.925,
        dec: 48.433,
        blurb: "M39, NGC 7092; Open cluster in the Cygnus Constellation, located 800 light years away.",
        magnitude: 4.6,
        sizeArcmin: 29,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -10,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m41: {
        id: "m41",
        name: "M41 — Little Beehive Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 101.5,
        dec: -20.767,
        blurb: "M41, NGC 2287; Open cluster in the Canis Major Constellation, located 2,300 light years away.",
        magnitude: 4.5,
        sizeArcmin: 38,
        minAltitudeDeg: 27,
        maxSunAltitudeDeg: -15,
        maxCloudPct: 40,
        maxMoonIllum: 0.65,
    },
    m52: {
        id: "m52",
        name: "M52 — Scorpion Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 351.05,
        dec: 61.583,
        blurb: "M52, NGC 7654; Open cluster in the Cassiopeia Constellation, located 5,000 light years away.",
        magnitude: 7.3,
        sizeArcmin: 13,
        minAltitudeDeg: 25,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 30,
        maxMoonIllum: 0.7,
    },
    m55: {
        id: "m55",
        name: "M55 — Specter Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 294.999,
        dec: -30.965,
        blurb: "M55, NGC 6809; Globular cluster in the Sagittarius Constellation, located 17,600 light years away.",
        magnitude: 6.3,
        sizeArcmin: 19,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m62: {
        id: "m62",
        name: "M62 — Flickering Globular",
        kind: "cluster",
        interest: "Stars",
        ra: 255.303,
        dec: -30.112,
        blurb: "M62, NGC 6266; Globular cluster in the Ophiuchus Constellation, located 22,200 light years away.",
        magnitude: 6.5,
        sizeArcmin: 15,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.8,
    },
    m67: {
        id: "m67",
        name: "M67 — King Cobra Cluster",
        kind: "cluster",
        interest: "Stars",
        ra: 132.825,
        dec: 11.817,
        blurb: "M67, NGC 2682; Open cluster in the Cancer Constellation, located 2,700 light years away.",
        magnitude: 6.1,
        sizeArcmin: 30,
        minAltitudeDeg: 20,
        maxSunAltitudeDeg: -12,
        maxCloudPct: 35,
        maxMoonIllum: 0.6,
    },
};

export const ICONS: Record<Target["kind"], IconName> = {
    planet: "planet",
    moon: "moon",
    sun: "sun",
    star: "astroid",
    galaxy: "orbit",
    nebula: "nebula",
    cluster: "astroid",
};
